import LaboratoryTestCategory from '../models/LaboratoryTestCategory.js';import LaboratoryTest from '../models/LaboratoryTest.js';import LaboratorySettings from '../models/LaboratorySettings.js';import SampleType from '../models/SampleType.js';import StockItem from '../models/StockItem.js';import {AppError} from '../utils/appError.js';import {emit} from '../services/sseService.js';
const catalog=[['HEMATOLOGY and IMMUNO HEMATOLOGY',['Complete Blood Count with Differential Count','Peripheral Morphology','Reticulocyte Count','Blood Group and RH','CD4 Count',"Coomb's Test",'Coagulation Profile (PT, aPTT, INR, D-Dimer, Fibrinogen, Bleeding Time, Clotting Time)','ESR'],'Whole Blood'],['CLINICAL CHEMISTRY and IMMUNOASSAY TESTS',['Renal Function Test','Lipid Profile','Liver Function Test','Uric Acid','Serum Electrolyte','Cardiac Tests','Oncology Tests / Tumor Markers','Fertility Tests','Thyroid Function Tests','Diabetic Tests','Quantitative Protein Tests','CSF & 24 Hour Urine Protein'],'Serum'],['URINE AND BODY FLUID ANALYSIS',['Urine Microscopy','Urine Chemical Test','Body Fluid Analysis'],'Urine'],['PARASITOLOGY',['Stool Examination','Hemoparasite','Filarial Parasite Identification','Modified Acid Fast Stain'],'Stool'],['MICROBIOLOGY',['Bacterial Culture & DST','Fungal Culture','Tuberculosis Culture & DST','Gram Stain','AFB Stain','Indian Ink'],'Body Fluids'],['SEROLOGICAL TESTS',['Widal-Weil Felix','H. Pylori Test','RPR','CRP','ASO','RF','Beta HCG','ANA','Fecal Occult Blood','Viral Infectious Tests'],'Serum'],['REFERRAL TESTS',[],'Serum'],['OTHER TESTS',['Viral Load Tests','COVID-19 RT-PCR','Serum Electrophoresis','OGTT','Semen Analysis','Drug Test'],'Serum']];
const referralTests=[['CA-125',2000],['CA-19',2000],['ANTI MULLERIAN HORMONE',4124],['ANA Titer 1100',2750],['Anti dsDNA',2755],['ANTI CYCLIC CITRULLINATATED PEPTIDE 2000',3100],['CA 15-3',2000],['CD4',4800],['Cortisol Serum',2200],['Ferratin or Folate',1680],['HBV Viral Load',4180],['HCV Viral Load',3880],['HCV Genotype',8100],['Hepatitis C Screen',1430],['HIV Viral Load',3360],['HIV 1 RNA Quantitative',3360],['Lipase',1700],['PTH',2000],['Testosterone',2000],['Vitamin B12',2000],['Female Cancer Markers',4400],['Male Cancer Marker',6000],['Vit B12 & Folate',2900],['Hepatitis B Surface Quantitative (10 Days)',5405]];
const escapeRegex=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
async function seedReferralTests(){const category=await LaboratoryTestCategory.findOne({name:/referral/i});if(!category)return;await LaboratoryTest.bulkWrite(referralTests.map(([name,price],displayOrder)=>({updateOne:{filter:{category:category._id,name:new RegExp(`^${escapeRegex(name)}$`,'i')},update:{$set:{price},$setOnInsert:{name,category:category._id,displayOrder,status:'Active',description:'',requiredSampleTypes:[]}},upsert:true}})),{ordered:true});}
async function seed(){if(!await LaboratoryTestCategory.exists()){const samples=await SampleType.find({});for(let i=0;i<catalog.length;i++){const [name,tests,sampleName]=catalog[i],category=await LaboratoryTestCategory.create({name,displayOrder:i});let sample=samples.find(x=>x.name.toLowerCase()===sampleName.toLowerCase());if(name==='URINE AND BODY FLUID ANALYSIS')sample=samples.find(x=>x.name.toLowerCase()==='urine');await LaboratoryTest.insertMany(tests.map((test,displayOrder)=>({name:test,category:category.id,requiredSampleTypes:sample?[sample.id]:[],displayOrder})));}await LaboratorySettings.findOneAndUpdate({key:'default'},{$setOnInsert:{key:'default'}},{upsert:true});}await seedReferralTests();}
export async function publicCatalog(req,res,next){try{await seed();const [categories,settings]=await Promise.all([LaboratoryTestCategory.find({status:'Active',hidden:false}).sort({displayOrder:1}),LaboratorySettings.findOne({key:'default'})]);const tests=await LaboratoryTest.find({status:'Active',category:{$in:categories.map(x=>x.id)}}).populate('requiredSampleTypes','name').sort({displayOrder:1});res.json({categories:categories.map(c=>({...c.toObject(),tests:tests.filter(t=>String(t.category)===String(c.id))})),settings})}catch(e){next(e)}}
export async function adminCatalog(req,res,next){try{await seed();const [categories,tests,settings,samples,stockItems]=await Promise.all([LaboratoryTestCategory.find().sort({displayOrder:1}),LaboratoryTest.find().populate('category','name').populate('requiredSampleTypes','name').populate('consumables.item','itemName unit').sort({displayOrder:1}),LaboratorySettings.findOne({key:'default'}),SampleType.find().select('name'),StockItem.find({status:'Active'}).select('itemName unit').sort({itemName:1})]);res.json({categories,tests,settings,samples,stockItems})}catch(e){next(e)}}
export async function createCategory(req,res,next){try{const category=await LaboratoryTestCategory.create(req.body);emit('laboratory-tests:change',{});res.status(201).json({category})}catch(e){next(e)}}
export async function updateCategory(req,res,next){try{const category=await LaboratoryTestCategory.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!category)throw new AppError('Category not found.',404);emit('laboratory-tests:change',{});res.json({category})}catch(e){next(e)}}
export async function deleteCategory(req,res,next){try{if(await LaboratoryTest.exists({category:req.params.id}))throw new AppError('Delete or move its tests first.',422);await LaboratoryTestCategory.findByIdAndDelete(req.params.id);emit('laboratory-tests:change',{});res.status(204).send()}catch(e){next(e)}}
export async function createTest(req,res,next){try{const test=await LaboratoryTest.create(req.body);emit('laboratory-tests:change',{});res.status(201).json({test})}catch(e){next(e)}}
export async function updateTest(req,res,next){try{const test=await LaboratoryTest.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!test)throw new AppError('Laboratory test not found.',404);emit('laboratory-tests:change',{});res.json({test})}catch(e){next(e)}}
export async function deleteTest(req,res,next){try{await LaboratoryTest.findByIdAndDelete(req.params.id);emit('laboratory-tests:change',{});res.status(204).send()}catch(e){next(e)}}
export async function getSettings(req,res,next){try{const settings=await LaboratorySettings.findOne({key:'default'});res.json({settings:settings||{}})}catch(e){next(e)}}
export async function updateSettings(req,res,next){try{const settings=await LaboratorySettings.findOneAndUpdate({key:'default'},req.body,{new:true,upsert:true,runValidators:true});emit('laboratory-tests:change',{});res.json({settings})}catch(e){next(e)}}
