import StockItem from '../models/StockItem.js'; import Category from '../models/Category.js'; import StockHistory from '../models/StockHistory.js'; import { AppError } from '../utils/appError.js'; import { nextItemCode, notifyStockLevel, recordHistory } from '../services/stockService.js'; import { stockLevel } from '../constants/stock.js';
const serialize=(item)=>{const data=item.toJSON?item.toJSON():item;return {...data,remainingQuantity:data.currentQuantity-data.usedQuantity,stockLevel:stockLevel(data)}};
export async function listItems(req,res,next){try{const {page=1,limit=15,search='',category,status,level,sort='newest',dateFrom,dateTo}=req.query;const filter={};if(category)filter.category=category;if(status)filter.status=status;if(search)filter.$or=[{itemName:{$regex:search,$options:'i'}},{itemCode:{$regex:search,$options:'i'}}];if(dateFrom||dateTo)filter.createdDate={...(dateFrom?{$gte:new Date(dateFrom)}:{}),...(dateTo?{$lte:new Date(`${dateTo}T23:59:59.999Z`)}:{})};const sortMap={newest:{createdDate:-1},oldest:{createdDate:1},name:{itemName:1},category:{category:1},remaining:{currentQuantity:1},price:{purchasePrice:1}};let items=await StockItem.find(filter).populate('category','name status').sort(sortMap[sort]||sortMap.newest).skip((Math.max(1,+page)-1)*Math.min(100,+limit)).limit(Math.min(100,+limit));if(level)items=items.filter((item)=>serialize(item).stockLevel.key===level);const total=await StockItem.countDocuments(filter);res.json({items:items.map(serialize),pagination:{page:+page,limit:+limit,total,pages:Math.ceil(total/Math.min(100,+limit))}});}catch(e){next(e)}}
export async function getItem(req,res,next){try{const item=await StockItem.findById(req.params.id).populate('category','name status');if(!item)throw new AppError('Stock item not found.',404);res.json({item:serialize(item)});}catch(e){next(e)}}
export async function createItem(req,res,next){try{if(!await Category.exists({_id:req.body.category,status:'Active'}))throw new AppError('Select an active category.',422);const item=await StockItem.create({...req.body,itemCode:await nextItemCode()});await recordHistory({item,action:'Created',user:req.user.id,snapshot:serialize(item),reason:'Stock item created'});await notifyStockLevel(item);res.status(201).json({item:serialize(item)});}catch(e){next(e)}}
export async function updateItem(req,res,next){try{if(!await Category.exists({_id:req.body.category}))throw new AppError('Category not found.',422);const before=await StockItem.findById(req.params.id);if(!before)throw new AppError('Stock item not found.',404);const item=await StockItem.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});await recordHistory({item,action:'Updated',user:req.user.id,snapshot:{before:serialize(before),after:serialize(item)},reason:'Item details updated'});await notifyStockLevel(item);res.json({item:serialize(item)});}catch(e){next(e)}}
export async function updateQuantity(req,res,next){try{const item=await StockItem.findById(req.params.id);if(!item)throw new AppError('Stock item not found.',404);const previous=item.currentQuantity-item.usedQuantity;item.currentQuantity=req.body.currentQuantity;item.usedQuantity=req.body.usedQuantity;await item.save();const current=item.currentQuantity-item.usedQuantity;await recordHistory({item,action:'Quantity Changed',user:req.user.id,previousQuantity:previous,newQuantity:current,reason:req.body.reason,field:'remainingQuantity'});await notifyStockLevel(item);res.json({item:serialize(item)});}catch(e){next(e)}}
export async function deleteItem(req,res,next){try{const item=await StockItem.findById(req.params.id);if(!item)throw new AppError('Stock item not found.',404);await recordHistory({item,action:'Deleted',user:req.user.id,snapshot:serialize(item),reason:'Stock item deleted'});await item.deleteOne();res.status(204).send();}catch(e){next(e)}}
export async function itemHistory(req,res,next){try{const history=await StockHistory.find({item:req.params.id}).populate('user','fullName username').sort({createdDate:-1});res.json({history});}catch(e){next(e)}}
export async function summary(req,res,next){try{const items=await StockItem.find({status:'Active'});const tally={totalItems:items.length,healthy:0,low:0,critical:0,outOfStock:0};const criticalItems=[];for(const item of items){const level=stockLevel(item);if(level.key==='Healthy')tally.healthy++;else if(level.key==='Out of Stock')tally.outOfStock++;else if(['Critical','Critical Emergency'].includes(level.key)){tally.critical++;criticalItems.push(serialize(item));}else tally.low++;}res.json({totalCategories:await Category.countDocuments(),...tally,criticalItems});}catch(e){next(e)}}
