/**
 * ETU Diagnostic Laboratory — Option C Standardized Clinical Radiology Templates
 * Consolidated from clinical reference packages (MRI, CT, Ultrasound).
 * Clean, standardized clinical reporting library with pre-populated techniques & normal findings.
 */

export const RADIOLOGY_TEMPLATES = {
  "MRI": [
    {
      "key": "brain_mri",
      "name": "Brain MRI",
      "category": "MRI",
      "examination": "BRAIN MRI",
      "clinicalInformation": "Headache, neurological deficit, rule out intracranial pathology.",
      "technique": "Multiplanar multisequential MRI of the brain was acquired without IV contrast using Axial T1, T2, FLAIR, DWI/ADC, T2* GRE, and Sagittal T1 sequences.",
      "comparison": "None available.",
      "findings": "BRAIN PARENCHYMA:\nThe cerebral hemispheres demonstrate symmetric morphology with normal gray-white matter differentiation.\nNo focal parenchymal signal intensity abnormality, acute territorial infarction, or restricted diffusion on DWI/ADC.\nNo intracranial hemorrhage, mass lesion, or midline shift.\n\nVENTRICLES & CISTERNS:\nThe lateral, third, and fourth ventricles are normal in size, shape, and configuration.\nBasal cisterns, sylvian fissures, and cortical sulcal spaces are unremarkable with no hydrocephalus or herniation.\n\nBASAL GANGLIA & THALAMI:\nThe basal ganglia, internal capsules, and thalami are symmetric with preserved signal characteristics.\n\nPOSTERIOR FOSSA:\nThe brainstem (midbrain, pons, and medulla) and cerebellar hemispheres show normal morphology and signal intensity.\nCerebellar tonsils lie comfortably above the level of the foramen magnum.\n\nVASCULAR FLOW VOIDS:\nMajor intracranial arterial flow voids at the skull base and Circle of Willis are preserved.\n\nORBITS & SINUSES:\nVisual pathways, retrobulbar intraorbital structures, and calvarium are unremarkable. Visualized paranasal sinuses and mastoid air cells are well aerated.",
      "impression": "Unremarkable / Normal Brain MRI study. No acute intracranial hemorrhage, territorial ischemia, mass effect, or midline shift identified.",
      "recommendation": "Clinical correlation advised.",
      "id": "brain_mri"
    },
    {
      "key": "cervical_spine_mri",
      "name": "Cervical Spine MRI",
      "category": "MRI",
      "examination": "CERVICAL SPINE MRI",
      "clinicalInformation": "Neck pain, cervical radiculopathy, numbness / paresthesia.",
      "technique": "Multiplanar MRI of the cervical spine acquired in Sagittal T1W, T2W, STIR, and Axial T2 and GRE sequences without intravenous contrast.",
      "comparison": "None available.",
      "findings": "ALIGNMENT & VERTEBRAL BODIES:\nNormal cervical lordosis and anatomic vertebral alignment.\nNormal vertebral body heights throughout the cervical and visualized upper thoracic spine.\nNormal bone marrow signal intensity; no evidence of destructive osseous lesion, fracture, or pathological edema.\n\nSPINAL CORD:\nThe cervical spinal cord demonstrates normal caliber, course, and signal intensity throughout.\nNo intrinsic focal lesions, syrinx, myelomalacia, or cord compression.\n\nINTERVERTEBRAL DISCS & NEURAL FORAMINA:\nC2-C3: Normal disc height and signal. Thecal sac and neural exit foramina are patent.\nC3-C4: Disc height and contour are preserved. No significant canal stenosis or foraminal narrowing.\nC4-C5: No disc herniation or nerve root impingement. Central spinal canal and neural foramina remain widely patent.\nC5-C6: Disc height and hydration are preserved. No focal posterior disc bulge, protrusion, or canal compromise.\nC6-C7: No significant disc protrusion or facet hypertrophy. Exit foramina are clear bilaterally.\nC7-T1: Unremarkable disc space and neural exit foramina.\n\nSOFT TISSUES & CRANIOCERVICAL JUNCTION:\nVisualized posterior fossa structures, craniocervical junction, and pre/paravertebral soft tissues are unremarkable without mass or fluid collection.",
      "impression": "Normal Cervical Spine MRI. Preserved cervical spinal cord signal without evidence of spinal stenosis, significant disc herniation, or nerve root compression.",
      "recommendation": "Correlate clinically with physical findings.",
      "id": "cervical_spine_mri"
    },
    {
      "key": "lumbosacral_spine_mri",
      "name": "Lumbosacral Spine MRI",
      "category": "MRI",
      "examination": "LUMBOSACRAL SPINE MRI",
      "clinicalInformation": "Low back pain, lumbosacral radiculopathy / sciatica.",
      "technique": "Sagittal T1, T2, STIR and Axial T2-weighted multiplanar MRI images of the lumbosacral spine without intravenous contrast.",
      "comparison": "None available.",
      "findings": "ALIGNMENT & BONE MARROW:\nNormal lumbar lordosis and anatomic lumbosacral alignment. No listhesis or spondylolysis.\nNormal vertebral body heights across L1 through S1.\nBone marrow signal intensity of the lumbar vertebral bodies and sacrum is within normal limits; no edema, marrow infiltration, or compression fracture.\n\nCONUS MEDULLARIS & THECAL SAC:\nThe conus medullaris terminates at a normal anatomic level (L1-L2 junction) with normal caliber and homogeneous signal.\nThe cauda equina nerve roots are evenly distributed throughout the thecal sac.\n\nINTERVERTEBRAL DISCS & CANAL DIMENSIONS:\nL1-L2: Disc height and signal are preserved. Thecal sac and neural exit foramina are widely patent.\nL2-L3: Preserved disc height and hydration. No posterior disc protrusion, central canal stenosis, or foraminal compromise.\nL3-L4: No focal disc bulge or herniation. Normal ligamentum flavum and facet joints. Lateral recesses and exit foramina are clear.\nL4-L5: Normal disc contour and height. No central canal stenosis, lateral recess narrowing, or exiting L4 / traversing L5 nerve root impingement.\nL5-S1: Preserved disc space. The thecal sac and exit foramina are clear bilaterally with no S1 root compromise.\n\nSOFT TISSUES:\nPrevertebral, retroperitoneal, and paraspinal soft tissues are normal without mass or collection. Sacroiliac joints are unremarkable.",
      "impression": "Normal Lumbosacral Spine MRI study. Normal vertebral alignment, normal disc contours, and widely patent central spinal canal and exit foramina without disc herniation or nerve root impingement.",
      "recommendation": "Clinical correlation recommended.",
      "id": "lumbosacral_spine_mri"
    },
    {
      "key": "knee_mri",
      "name": "Knee MRI",
      "category": "MRI",
      "examination": "KNEE MRI",
      "clinicalInformation": "Knee pain, sports injury, rule out meniscal / ligamentous tear.",
      "technique": "Multiplanar, multisequential MRI of the knee acquired without IV contrast using Sagittal T1, Sagittal T2/PD FS, Coronal PD/T2 FS, and Axial T2 FS sequences.",
      "comparison": "None available.",
      "findings": "MENISCI:\nMedial Meniscus: Normal size, configuration, and low signal intensity throughout the anterior horn, body, and posterior horn. No signal extending to an articular surface; no tear.\nLateral Meniscus: Intact with normal shape and homogeneous low signal. No meniscal tear, maceration, or parameniscal cyst.\n\nCRUCIATE & COLLATERAL LIGAMENTS:\nAnterior Cruciate Ligament (ACL): Normal orientation, course, and taut fibrillar signal. Intact with no sprain or rupture.\nPosterior Cruciate Ligament (PCL): Smooth, continuous, and homogeneous low signal. Intact.\nMedial Collateral Ligament (MCL): Normal thickness and intact femoral and tibial attachments.\nLateral Collateral Ligament (LCL) Complex: Intact fibular collateral ligament, biceps femoris tendon, and popliteus tendon.\n\nEXTENSOR MECHANISM & PATELLOFEMORAL COMPARTMENT:\nQuadriceps tendon and patellar tendon are continuous with normal morphology and signal.\nPatellofemoral alignment is anatomic. Trochlear groove and patellar cartilage show smooth articular surfaces without defect.\nInfrapatellar fat pad (Hoffa's fat pad) and prepatellar soft tissues are unremarkable.\n\nCARTILAGE & OSSEOUS STRUCTURES:\nFemorotibial articular cartilage is intact and of uniform thickness in both medial and lateral compartments.\nNormal bone marrow signal in the distal femur, proximal tibia, and patella. No fracture, subchondral edema, or osteochondral defect.\n\nJOINT EFFUSION:\nPhysiologic amount of joint fluid. No significant joint effusion, intra-articular loose bodies, or popliteal (Baker's) cyst.",
      "impression": "Normal Knee MRI study. Intact medial and lateral menisci, normal cruciate (ACL, PCL) and collateral ligaments, and preserved articular cartilage without joint effusion or occult fracture.",
      "recommendation": "Clinical correlation recommended.",
      "id": "knee_mri"
    },
    {
      "key": "shoulder_mri",
      "name": "Shoulder MRI",
      "category": "MRI",
      "examination": "SHOULDER MRI",
      "clinicalInformation": "Shoulder pain, limited range of motion, rule out rotator cuff tear or impingement.",
      "technique": "Multiplanar multisequential MRI of the shoulder acquired using Coronal oblique T1/PD FS, Sagittal oblique T2 FS, and Axial PD/T2 FS without intravenous contrast.",
      "comparison": "None available.",
      "findings": "ROTATOR CUFF TENDONS:\nSupraspinatus Tendon: Normal caliber, course, and signal intensity with intact footprint insertion onto the greater tuberosity. No partial- or full-thickness tear.\nInfraspinatus & Teres Minor: Intact with normal signal and contour.\nSubscapularis Tendon: Normal insertion onto the lesser tuberosity with intact upper and lower fibers.\nRotator Cuff Musculature: Normal muscle bulk without atrophy, fatty infiltration, or edema.\n\nBICEPS TENDON & LABRUM:\nLong Head of Biceps Tendon: Centered within the bicipital groove with normal caliber and signal. Intact biceps anchor.\nGlenoid Labrum: Normal triangular low-signal configuration along the superior, anterior, inferior, and posterior labral margins. No SLAP or Bankart tear.\n\nGLENOHUMERAL & ACROMIOCLAVICULAR JOINTS:\nGlenohumeral joint space and articular cartilage are well preserved. Glenohumeral ligaments and capsule are intact.\nAcromioclavicular (AC) joint shows normal alignment without hypertrophic spurring or capsular thickening.\nSubacromial/subdeltoid bursa shows no abnormal fluid distension. Coracoacromial arch is unremarkable.\n\nOSSEOUS STRUCTURES:\nNormal bone marrow signal in the humeral head, glenoid, acromion, and clavicle. No fracture, bone contusion, Hill-Sachs or reverse Hill-Sachs lesion.",
      "impression": "Normal Shoulder MRI study. Intact rotator cuff tendons without tear, normal long head of biceps tendon, preserved glenoid labrum, and unremarkable AC and glenohumeral joints.",
      "recommendation": "Clinical correlation recommended.",
      "id": "shoulder_mri"
    },
    {
      "key": "ankle_mri",
      "name": "Ankle MRI",
      "category": "MRI",
      "examination": "ANKLE MRI",
      "clinicalInformation": "Ankle pain, inversion injury, instability, rule out ligamentous or tendon pathology.",
      "technique": "Multiplanar MRI of the ankle acquired in Sagittal T1, T2, STIR, Coronal T1, T2 FS, and Axial T2 FS sequences without intravenous contrast.",
      "comparison": "None available.",
      "findings": "LIGAMENTS:\nLateral Collateral Ligament Complex: Anterior talofibular ligament (ATFL), calcaneofibular ligament (CFL), and posterior talofibular ligament (PTFL) are intact with normal low signal and thickness.\nMedial Deltoid Ligament: Superficial and deep components are intact with normal architecture.\nSyndesmotic Ligaments: Anterior and posterior inferior tibiofibular ligaments and interosseous membrane are unremarkable.\n\nTENDONS:\nAchilles Tendon: Continuous with normal thickness and low signal throughout its course to the calcaneal insertion. Retrocalcaneal and retroachilles bursae are normal.\nPlantar Fascia: Normal thickness and signal at the calcaneal origin without plantar fasciitis.\nMedial Flexor Tendons (Tibialis posterior, FDL, FHL) and Lateral Peroneal Tendons (Brevis and Longus) maintain normal caliber, course, and signal within their retinacula.\nAnterior Extensor Tendons: Tibialis anterior, EHL, and EDL are normal.\n\nJOINTS & CARTILAGE:\nTibiotalar (ankle mortise) and subtalar joint spaces are preserved with smooth articular cartilage.\nNo osteochondral defect of the talar dome.\nPhysiologic amount of joint fluid without significant joint effusion or intra-articular loose bodies.\n\nOSSEOUS STRUCTURES:\nBone marrow signal intensity of the distal tibia, fibula, talus, and calcaneus is within normal limits. No occult fracture, bone contusion, or avulsion.",
      "impression": "Normal Ankle MRI study. Intact lateral and medial ligamentous complexes, normal Achilles and peroneal tendons, and preserved articular cartilage with no talar dome osteochondral lesion.",
      "recommendation": "Clinical correlation recommended.",
      "id": "ankle_mri"
    },
    {
      "key": "elbow_mri",
      "name": "Elbow MRI",
      "category": "MRI",
      "examination": "ELBOW MRI",
      "clinicalInformation": "Elbow pain, sports injury, rule out tendinopathy, epicondylitis, or ligament tear.",
      "technique": "Multiplanar multisequential MRI of the elbow acquired using Coronal T1/T2 FS, Sagittal T1/T2 FS, and Axial PD/T2 FS without intravenous contrast.",
      "comparison": "None available.",
      "findings": "TENDONS & MUSCLES:\nCommon Extensor Tendon: Normal origin at the lateral epicondyle without tendinosis, partial tear, or peritendinous edema.\nCommon Flexor Tendon: Normal origin at the medial epicondyle with preserved fibrillar architecture.\nBiceps and Brachialis Tendons: Distal biceps tendon inserts normally on the radial tuberosity. Brachialis insertion is intact.\nTriceps Tendon: Continuous and well-anchored to the olecranon process without tear or bursitis.\nMuscles about the elbow joint demonstrate normal signal and bulk.\n\nLIGAMENTOUS STRUCTURES:\nUlnar Collateral Ligament (UCL): Anterior and posterior bands are intact with normal thickness and low signal.\nRadial Collateral Ligament Complex: Radial collateral, lateral ulnar collateral, and annular ligaments are intact.\n\nJOINTS, CARTILAGE & NERVES:\nRadiohumeral, ulnohumeral, and proximal radioulnar joints show normal alignment and cartilage coverage.\nNo joint effusion or intra-articular loose bodies.\nCubital tunnel and ulnar nerve show normal caliber and signal without compression or subluxation.\nNormal bone marrow signal without occult fracture or bone contusion.",
      "impression": "Normal Elbow MRI study. Intact common extensor and flexor tendons, normal collateral ligaments, and unremarkable cubital tunnel and articular structures.",
      "recommendation": "Clinical correlation recommended.",
      "id": "elbow_mri"
    },
    {
      "key": "hip_mri",
      "name": "Hip MRI",
      "category": "MRI",
      "examination": "HIP MRI",
      "clinicalInformation": "Hip / groin pain, clicking, rule out labral tear or avascular necrosis (AVN).",
      "technique": "Multiplanar multisequential MRI images of the hip acquired without intravenous contrast.",
      "comparison": "None available.",
      "findings": "HIP JOINT & ARTICULAR CARTILAGE:\nNormal femoroacetabular alignment. Sphericity of the femoral head is preserved.\nFemoral head and acetabular articular cartilage are intact with uniform joint space.\nNo subchondral sclerosis, cyst formation, or osteophytosis.\nAcetabular labrum is triangular and homogeneous in low signal intensity; no labral tear or paralabral cyst.\n\nBONE MARROW:\nNormal bone marrow signal intensity in the femoral head, femoral neck, and acetabulum.\nNo evidence of avascular necrosis (AVN), bone marrow edema, stress fracture, or transient osteoporosis.\n\nTENDONS & SOFT TISSUES:\nGluteus medius and minimus tendons insert normally onto the greater trochanter. Trochanteric bursae show no fluid distension.\nIliopsoas tendon and bursa are unremarkable.\nMusculature about the hip joint demonstrates symmetric bulk and normal signal intensity.\nPhysiologic amount of joint fluid without significant joint effusion.",
      "impression": "Normal Hip MRI study. Normal femoral head sphericity and marrow signal without avascular necrosis (AVN), labral tear, or inflammatory/erosive arthropathy.",
      "recommendation": "Clinical correlation recommended.",
      "id": "hip_mri"
    },
    {
      "key": "pelvic_mri_female",
      "name": "Pelvic MRI — Female",
      "category": "MRI",
      "examination": "PELVIC MRI (FEMALE)",
      "clinicalInformation": "Pelvic pain, gynecological evaluation, rule out pelvic mass, fibroid, or endometriosis.",
      "technique": "High-resolution multiplanar pelvic MRI acquired in Sagittal T2, Axial T1, Axial T2, Axial T2 STIR, and Coronal T2 sequences without intravenous contrast.",
      "comparison": "None available.",
      "findings": "UTERUS & CERVIX:\nThe uterus is normal in size, shape, and anteverted in position.\nMyometrium demonstrates homogeneous normal signal intensity. No uterine leiomyoma (fibroid) or focal mass lesion.\nJunctional zone is sharp and of normal thickness.\nEndometrium is regular and symmetric with thickness appropriate for age / menstrual phase. No focal endometrial polyp or mass.\nThe cervix and endocervical canal are unremarkable without mass or stromal invasion.\n\nADNEXA & OVARIES:\nRight and left ovaries demonstrate normal volume, follicular activity, and signal intensity for age.\nNo ovarian mass, cystadenoma, endometrioma, or mature teratoma identified.\nNo free fluid or nodularity in the pouch of Douglas (cul-de-sac).\n\nBLADDER & RECTUM:\nUrinary bladder is well distended with normal, uniform wall thickness and smooth mucosal outline.\nRectum, mesorectal fascia, and perirectal fat are clear without mass or wall thickening.\n\nLYMPH NODES & BONES:\nNo pelvic, obturator, or inguinal lymphadenopathy.\nPelvic skeleton demonstrates normal bone marrow signal intensity and intact cortical margins.",
      "impression": "Normal Female Pelvic MRI. Normal uterus and bilateral ovaries without uterine fibroids, adnexal mass, endometriosis, or pelvic lymphadenopathy.",
      "recommendation": "Clinical correlation recommended.",
      "id": "pelvic_mri_female"
    },
    {
      "key": "pelvic_mri_male",
      "name": "Pelvic MRI — Male",
      "category": "MRI",
      "examination": "PELVIC MRI (MALE)",
      "clinicalInformation": "Elevated PSA, lower urinary tract symptoms (LUTS), pelvic evaluation.",
      "technique": "Multiplanar pelvic MRI acquired in Sagittal T2, Axial T1, Axial T2, Axial T2 STIR, and Coronal T2 sequences without intravenous contrast.",
      "comparison": "None available.",
      "findings": "PROSTATE GLAND & SEMINAL VESICLES:\nThe prostate gland demonstrates normal dimensions, contour, and zonal anatomy.\nPeripheral Zone (PZ): Uniform, homogeneous high signal intensity on T2W without suspicious focal hypointense lesions, capsular disruption, or extracapsular extension.\nTransition Zone (TZ): Normal volume and appearance without suspicious nodularity.\nSeminal vesicles are symmetric, well-distended, and show normal fluid signal intensity without invasion.\n\nURINARY BLADDER & RECTUM:\nUrinary bladder shows normal wall thickness without focal mass, diverticulum, or intraluminal lesion.\nRectum and mesorectum demonstrate normal wall caliber and signal. Mesorectal fat planes are preserved.\n\nLYMPH NODES & OSSEOUS STRUCTURES:\nNo pelvic, obturator, external iliac, or inguinal lymphadenopathy.\nIncluded pelvic girdle bones demonstrate normal marrow signal without focal osteoblastic or osteolytic metastasis.",
      "impression": "Normal Male Pelvic MRI study. Normal prostate gland zonal anatomy without focal peripheral zone lesion or extracapsular extension. No pelvic lymphadenopathy.",
      "recommendation": "Clinical correlation and PSA surveillance recommended.",
      "id": "pelvic_mri_male"
    },
    {
      "key": "thigh_hip_mri",
      "name": "Thigh & Hip MRI",
      "category": "MRI",
      "examination": "THIGH AND HIP MRI",
      "clinicalInformation": "Thigh pain, soft tissue mass evaluation, trauma, rule out tear or lesion.",
      "technique": "Multiplanar MRI of the hip and thigh acquired in Axial T1/T2/STIR, Coronal T1/T2, and Sagittal sequences.",
      "comparison": "None available.",
      "findings": "MUSCULATURE & COMPARTMENTS:\nAnterior, posterior, and medial muscle compartments of the thigh show normal muscle bulk and symmetric signal intensity.\nQuadriceps femoris, hamstrings, and adductor muscle groups are intact without strain, tear, or hematoma.\nIntermuscular fascial planes and neurovascular bundles are clearly defined and preserved.\n\nBONE & MARROW:\nThe proximal femur, femoral shaft, and hip joint demonstrate normal bone marrow signal intensity.\nNo fracture, subcortical lesion, stress reaction, or periosteal reaction.\n\nVASCULAR & SOFT TISSUE STRUCTURES:\nFemoral artery and vein show normal flow voids and course.\nNo focal cystic or solid soft tissue mass, abscess, or vascular malformation.",
      "impression": "Normal Thigh & Hip MRI. Intact thigh musculature and fascia without soft tissue mass, tear, hematoma, or osseous abnormality.",
      "recommendation": "Clinical correlation recommended.",
      "id": "thigh_hip_mri"
    },
    {
      "key": "mrv_head",
      "name": "MRV of the Head (Magnetic Resonance Venography)",
      "category": "MRI",
      "examination": "MR VENOGRAPHY (MRV) OF THE HEAD",
      "clinicalInformation": "Severe headache, papilledema, rule out cerebral venous sinus thrombosis (CVST).",
      "technique": "3D Time-of-Flight (TOF) / Phase Contrast MR Venography of the intracranial venous sinuses.",
      "comparison": "None available.",
      "findings": "DURAL VENOUS SINUSES:\nSuperior Sagittal Sinus (SSS): Fully patent throughout its anterior, middle, and posterior segments with normal venous flow signal. No filling defect.\nInferior Sagittal Sinus & Straight Sinus: Patent with smooth contour and normal flow void.\nTransverse Sinuses: Bilateral transverse sinuses demonstrate symmetric luminal patency and uniform flow signal. No focal thrombosis.\nSigmoid Sinuses: Patent bilaterally extending to the jugular bulbs.\nConfluence of Sinuses (Torcular Herophili): Normal anatomic confluence with continuous flow signal.\n\nINTERNAL CEREBRAL VEINS & JUGULAR BULBS:\nVein of Galen, internal cerebral veins, and basal veins of Rosenthal are patent.\nBilateral internal jugular veins show normal flow signal without intraluminal thrombosis.",
      "impression": "Normal MR Venography of the Head. Widely patent dural venous sinuses (superior sagittal, straight, transverse, and sigmoid sinuses) without evidence of cerebral venous sinus thrombosis (CVST).",
      "recommendation": "Clinical correlation recommended.",
      "id": "mrv_head"
    }
  ],
  "CT": [
    {
      "key": "head_ct",
      "name": "Head CT (Brain CT)",
      "category": "CT",
      "examination": "HEAD CT (NON-CONTRAST)",
      "clinicalInformation": "Headache, trauma, altered mental status, rule out acute intracranial hemorrhage or stroke.",
      "technique": "Axial contiguous volumetric non-contrast CT scans of the head acquired from the skull base to the vertex with multiplanar reconstructions.",
      "comparison": "None available.",
      "findings": "BRAIN PARENCHYMA:\nNormal symmetric cerebral and cerebellar hemispheres with preserved gray-white matter differentiation.\nNo acute intra-axial or extra-axial hemorrhage (epidural, subdural, subarachnoid, or intraventricular).\nNo territorial hypoattenuation to indicate acute major vascular territory infarction.\nNo focal mass lesion, mass effect, or midline shift.\n\nVENTRICULAR SYSTEM & CISTERNS:\nThe lateral, third, and fourth ventricles are symmetric and normal in size for age.\nBasal cisterns, sylvian fissures, and cortical sulcal spaces are preserved without effacement.\n\nPOSTERIOR FOSSA:\nThe brainstem and cerebellum demonstrate normal attenuation and morphology.\n\nCALVARIUM & BONES:\nCalvarial bones, skull base, and facial structures are intact without fracture.\nVisualized paranasal sinuses and mastoid air cells are well aerated without fluid levels.",
      "impression": "Normal Non-Contrast Head CT study. No acute intracranial hemorrhage, territorial acute ischemic infarction, mass effect, or skull fracture.",
      "recommendation": "Clinical correlation recommended.",
      "id": "head_ct"
    },
    {
      "key": "head_neck_ct",
      "name": "Head & Neck CT",
      "category": "CT",
      "examination": "HEAD AND NECK CT",
      "clinicalInformation": "Trauma, neck swelling, neurological symptoms, staging evaluation.",
      "technique": "Volumetric CT scan from the vertex to the thoracic inlet with axial slices and multiplanar sagittal/coronal reconstructions.",
      "comparison": "None available.",
      "findings": "HEAD & INTRACRANIAL STRUCTURES:\nBrain parenchyma demonstrates symmetric gray-white differentiation.\nNo acute hemorrhage, territorial infarct, mass effect, or midline shift.\nVentricular system and basal cisterns are normal in size and configuration.\n\nNECK VISCERAL SPACES & AIRWAY:\nNasopharynx, oropharynx, and hypopharynx demonstrate symmetric mucosal outlines with patent airway.\nLarynx and subglottic airway are clear. Major salivary glands (parotid and submandibular) are symmetric and homogeneous.\nThyroid gland is normal in size and attenuation without suspicious discrete nodules or substernal extension.\n\nCERVICAL LYMPH NODES & VESSELS:\nNo pathologically enlarged lymph nodes in cervical nodal stations I through VII.\nCarotid arteries and internal jugular veins demonstrate normal caliber and course bilaterally.\n\nBONES:\nSkull base, facial skeleton, and cervical spine demonstrate intact cortical margins without traumatic fracture or aggressive osseous lesion.",
      "impression": "Normal Head & Neck CT study. No acute intracranial abnormality or cervical mass/lymphadenopathy. Patent upper airway.",
      "recommendation": "Clinical correlation recommended.",
      "id": "head_neck_ct"
    },
    {
      "key": "chest_ct",
      "name": "Chest CT (Thoracic CT)",
      "category": "CT",
      "examination": "CHEST CT (THORACIC CT)",
      "clinicalInformation": "Chronic cough, dyspnea, chest pain, rule out pulmonary infection, mass, or interstitial disease.",
      "technique": "Volumetric helical CT of the thorax acquired from the lung apices to the adrenal glands with high-resolution lung and mediastinal window reconstructions.",
      "comparison": "None available.",
      "findings": "LUNG PARENCHYMA & AIRWAYS:\nBilateral lungs are clear and symmetrically expanded.\nNo focal consolidation, ground-glass opacities, suspicious pulmonary nodule, or mass.\nTrachea, main bronchi, and segmental bronchi are patent with normal branching pattern. No bronchiectasis or airway wall thickening.\n\nPLEURA:\nNo pneumothorax, pleural effusion, or pleural thickening bilaterally.\n\nMEDIASTINUM & HILA:\nMediastinal contour and compartments are normal.\nHeart size is within normal limits. Pericardium is unremarkable without effusion.\nAscending aorta, aortic arch, descending aorta, and pulmonary trunk demonstrate normal caliber and morphology.\nNo pathologically enlarged mediastinal or hilar lymph nodes.\n\nCHEST WALL & BONES:\nRib cage, sternum, clavicles, and thoracic spine are intact without fracture or destructive osseous lesion.\nVisualized upper abdominal structures, including the liver and adrenal glands, are unremarkable.",
      "impression": "Normal Chest CT study. Clear lung parenchyma without pulmonary nodules, consolidation, pleural effusion, or mediastinal lymphadenopathy.",
      "recommendation": "Clinical correlation recommended.",
      "id": "chest_ct"
    },
    {
      "key": "abdomen_pelvis_ct",
      "name": "Abdomen & Pelvis CT",
      "category": "CT",
      "examination": "ABDOMEN AND PELVIS CT",
      "clinicalInformation": "Abdominal pain, distension, rule out acute intra-abdominal pathology or mass.",
      "technique": "Contrast-enhanced / volumetric helical CT of the abdomen and pelvis from the diaphragm to the pubic symphysis with axial, sagittal, and coronal MPR.",
      "comparison": "None available.",
      "findings": "SOLID ORGANS:\nLiver: Normal in size and contour with homogeneous parenchymal attenuation. No focal hepatic lesion or intrahepatic biliary dilatation.\nGallbladder & Biliary Tree: Gallbladder is well-distended with thin wall; no radiopaque gallstones. Extrahepatic bile duct is of normal caliber.\nSpleen: Normal size and homogeneous attenuation without focal lesion or laceration.\nPancreas: Normal parenchymal volume and enhancement without peripancreatic fat stranding, fluid collection, or ductal dilatation.\nAdrenal Glands: Bilateral adrenal glands have normal limb morphology and attenuation without nodule or hyperplasia.\nKidneys & Ureters: Bilateral kidneys are normal in size and position with prompt, symmetric nephrograms. No hydronephrosis, calculus, or mass. Visualized ureters are unremarkable.\n\nGASTROINTESTINAL TRACT:\nStomach and duodenum demonstrate normal wall thickness.\nSmall bowel loops and colon are unremarkable in caliber and enhancement without obstruction, wall thickening, or inflammatory stranding.\nAppendix is visualized and normal in caliber (<6 mm) without periappendiceal fat stranding.\n\nPELVIC VISCERA:\nUrinary bladder has smooth, thin wall without intraluminal filling defect.\nPelvic genital organs are unremarkable for age and sex.\n\nPERITONEUM, RETROPERITONEUM & VESSELS:\nNo ascites, free intra-abdominal fluid, or free intraperitoneal air (pneumoperitoneum).\nNo mesenteric or retroperitoneal lymphadenopathy.\nAbdominal aorta and inferior vena cava demonstrate normal course and caliber.\n\nBONES:\nVisualized spine, pelvic girdle, and ribs show normal mineral density without acute fracture or aggressive osteolytic/osteoblastic lesion.",
      "impression": "Normal Abdomen & Pelvis CT study. Normal solid abdominal viscera, clear gastrointestinal tract without obstruction or appendicitis, and no ascites, free air, or lymphadenopathy.",
      "recommendation": "Clinical correlation recommended.",
      "id": "abdomen_pelvis_ct"
    },
    {
      "key": "abdomen_chest_ct",
      "name": "Abdomen & Chest CT (Thoracoabdominal CT)",
      "category": "CT",
      "examination": "ABDOMEN AND CHEST CT",
      "clinicalInformation": "Staging evaluation, polytrauma, constitutional symptoms.",
      "technique": "Helical volumetric CT from the lung apices through the pubic symphysis with multiplanar reconstructions.",
      "comparison": "None available.",
      "findings": "THORACIC CAVITY:\nLungs are clear bilaterally with no pulmonary nodule, mass, consolidation, or interstitial changes.\nNo pleural effusion or pneumothorax.\nHeart size and pericardium are unremarkable. Great vessels show normal caliber.\nNo mediastinal, hilar, or axillary lymphadenopathy.\n\nABDOMINAL & PELVIC VISCERA:\nLiver, gallbladder, spleen, pancreas, adrenals, and kidneys are normal in size and attenuation without focal lesion or ductal dilatation.\nBowel loops are normal in caliber without wall thickening or obstruction.\nUrinary bladder and pelvic organs are unremarkable.\nNo free fluid, free air, or retroperitoneal lymphadenopathy.\n\nSKELETON:\nThoracic and lumbosacral spine, ribs, and pelvic bones show no acute fracture or suspicious osteolytic lesion.",
      "impression": "Normal Chest, Abdomen, and Pelvis CT study. No evidence of thoracic or intra-abdominal neoplastic, infectious, or acute traumatic pathology.",
      "recommendation": "Clinical correlation recommended.",
      "id": "abdomen_chest_ct"
    },
    {
      "key": "neck_ct",
      "name": "Neck CT (Soft Tissue Neck)",
      "category": "CT",
      "examination": "NECK CT (CONTRAST-ENHANCED)",
      "clinicalInformation": "Neck mass, hoarseness, dysphagia, cervical lymphadenopathy evaluation.",
      "technique": "Axial contiguous volumetric CT of the soft tissues of the neck from the skull base to the carina with sagittal and coronal MPR.",
      "comparison": "None available.",
      "findings": "AERODIGESTIVE TRACT:\nNasopharynx, oropharynx, and hypopharynx demonstrate symmetric mucosal contours and patent airway.\nSupraglottic and glottic structures are symmetric. True vocal cords are normal in position and contour. Subglottic airway is clear.\n\nSALIVARY GLANDS & THYROID:\nBilateral parotid and submandibular glands are symmetric with normal parenchymal attenuation. No sialolithiasis or mass.\nThyroid gland is normal in size and position with symmetric lobes and homogeneous enhancement.\n\nLYMPH NODES & FASCIAL SPACES:\nNo pathologically enlarged lymph nodes in cervical levels I through VII.\nRetropharyngeal, parapharyngeal, and masticator spaces are symmetric without mass or collection.\n\nVASCULATURE & OSSEOUS STRUCTURES:\nCommon carotid arteries, internal carotid arteries, and internal jugular veins are patent with normal caliber.\nVisualized cervical spine and skull base show no destructive osseous lesion or acute fracture.",
      "impression": "Normal Soft Tissue Neck CT. Symmetric aerodigestive tract, normal thyroid and salivary glands, patent vessels, and no pathologically enlarged cervical lymph nodes.",
      "recommendation": "Clinical correlation recommended.",
      "id": "neck_ct"
    },
    {
      "key": "cervical_spine_ct",
      "name": "Cervical Spine CT",
      "category": "CT",
      "examination": "CERVICAL SPINE CT",
      "clinicalInformation": "Neck trauma, pain, rule out cervical spine fracture or subluxation.",
      "technique": "Thin-slice volumetric axial CT from the skull base to T2 with sagittal and coronal multiplanar reconstructions.",
      "comparison": "None available.",
      "findings": "ALIGNMENT & VERTEBRAE:\nNormal cervical lordosis and vertebral alignment. Craniocervical junction (dens, atlas, and axis) is intact.\nVertebral body heights and posterior element architecture (pedicles, laminae, spinous processes) are preserved throughout C1 to C7.\nNo acute cortical fracture, displacement, or subluxation.\n\nSPINAL CANAL & DISC SPACES:\nSpinal canal dimensions are adequate with no bony canal narrowing or retropulsed fragments.\nIntervertebral disc spaces are preserved. Uncovertebral and facet joints are unremarkable with no dislocation.\nNeural exit foramina are widely patent bilaterally.\n\nSOFT TISSUES:\nPrevertebral and paravertebral soft-tissue thicknesses are within normal limits with no prevertebral hematoma.",
      "impression": "Normal Cervical Spine CT. Anatomic cervical alignment without traumatic fracture, subluxation, or canal compromise.",
      "recommendation": "Clinical correlation recommended.",
      "id": "cervical_spine_ct"
    },
    {
      "key": "cervical_thoracic_spine_ct",
      "name": "Cervical & Thoracic Spine CT",
      "category": "CT",
      "examination": "CERVICAL AND THORACIC SPINE CT",
      "clinicalInformation": "Spinal trauma, multiple level back pain, rule out fracture.",
      "technique": "Helical volumetric CT from the skull base through T12 with multiplanar reconstructions.",
      "comparison": "None available.",
      "findings": "ALIGNMENT & OSSEOUS ARCHITECTURE:\nNormal cervical and thoracic spinal alignment. No kyphotic angulation or step-off deformity.\nVertebral body heights of all cervical and thoracic vertebrae are intact without compression deformity.\nPedicles, laminae, transverse processes, and spinous processes are intact without fracture.\nCostovertebral and costotransverse joints are normal.\n\nCANAL & FORAMINA:\nCentral bony spinal canal is widely patent throughout without stenosis or fragment retropulsion.\nNeural exit foramina are patent bilaterally.\nPrevertebral and paraspinal soft tissues are normal without hematoma or mass.",
      "impression": "Normal Cervical and Thoracic Spine CT study. No traumatic fracture, dislocation, or canal encroachment.",
      "recommendation": "Clinical correlation recommended.",
      "id": "cervical_thoracic_spine_ct"
    },
    {
      "key": "lumbosacral_spine_ct",
      "name": "Lumbosacral Spine CT",
      "category": "CT",
      "examination": "LUMBOSACRAL SPINE CT",
      "clinicalInformation": "Lower back pain, trauma, sciatica, rule out osseous fracture or stenosis.",
      "technique": "Axial volumetric CT of the lumbar and sacral spine from T12 to S2 with sagittal and coronal MPR.",
      "comparison": "None available.",
      "findings": "ALIGNMENT & VERTEBRAE:\nAnatomic lumbar alignment with preserved lordosis. No spondylolysis or spondylolisthesis.\nVertebral body heights across L1 to S1 are well maintained without acute fracture or height loss.\nPosterior elements (pedicles, laminae, pars interarticularis, spinous processes) are intact.\n\nINTERVERTEBRAL DISCS & JOINTS:\nIntervertebral disc space heights are preserved.\nFacet joints and sacroiliac joints demonstrate normal articulation without significant arthropathy.\nBony central canal and neural exit foramina are widely patent without osseous stenosis.\n\nSOFT TISSUES:\nPsoas muscles and paraspinal soft tissues are symmetric and unremarkable.",
      "impression": "Normal Lumbosacral Spine CT. No traumatic fracture, subluxation, spondylolysis, or osseous canal stenosis.",
      "recommendation": "Clinical correlation recommended.",
      "id": "lumbosacral_spine_ct"
    },
    {
      "key": "thoracolumbar_spine_ct",
      "name": "Thoracolumbar Spine CT",
      "category": "CT",
      "examination": "THORACOLUMBAR SPINE CT",
      "clinicalInformation": "Fall / trauma, mid-back pain, rule out thoracolumbar junction compression fracture.",
      "technique": "Helical volumetric CT from T9 through L5 with multiplanar sagittal and coronal reconstructions.",
      "comparison": "None available.",
      "findings": "ALIGNMENT & BONE INTEGRITY:\nAnatomic thoracolumbar alignment. Normal transition curvature at the T12-L1 junction.\nVertebral body heights of T9 through L5 are well preserved without anterior wedge compression or burst fracture.\nPosterior cortical walls of the vertebral bodies are intact with no retropulsion.\nPedicles, facets, and spinous processes are intact.\n\nSPINAL CANAL:\nThe bony spinal canal demonstrates normal anteroposterior and transverse diameters.\nNeural exit foramina are patent bilaterally.\nParaspinal soft tissues show no hematoma or mass.",
      "impression": "Normal Thoracolumbar Spine CT study. No acute fracture, displacement, or bony spinal canal compromise.",
      "recommendation": "Clinical correlation recommended.",
      "id": "thoracolumbar_spine_ct"
    },
    {
      "key": "thoracolumbar_pelvic_ct",
      "name": "Thoracolumbar & Pelvic CT",
      "category": "CT",
      "examination": "THORACOLUMBAR AND PELVIC CT",
      "clinicalInformation": "High-energy trauma, polytrauma, pelvic and back pain evaluation.",
      "technique": "Helical volumetric CT from mid-thoracic spine through the ischial tuberosities with 3D bone and MPR reconstructions.",
      "comparison": "None available.",
      "findings": "THORACOLUMBAR SPINE:\nNormal thoracolumbar alignment without subluxation or fracture.\nVertebral body heights and posterior arch elements are intact. Bony canal is clear.\n\nPELVIC GIRDLE & BONES:\nThe pelvic ring is intact.\nBilateral sacroiliac joints, iliac wings, pubic rami, and symphysis pubis show normal alignment without diastasis or fracture.\nBoth acetabula and femoral heads demonstrate normal congruity with no occult fracture or dislocation.\n\nPELVIC SOFT TISSUES:\nObturator internus and pelvic floor musculature are symmetric. No pelvic hematoma or active contrast extravasation.",
      "impression": "Normal Thoracolumbar & Pelvic CT. Intact thoracolumbar spine and pelvic ring without traumatic fracture or dislocation.",
      "recommendation": "Clinical correlation recommended.",
      "id": "thoracolumbar_pelvic_ct"
    },
    {
      "key": "cta_head_neck",
      "name": "CTA Head & Neck (CT Angiography)",
      "category": "CT",
      "examination": "HEAD AND NECK CT ANGIOGRAPHY (CTA)",
      "clinicalInformation": "Vascular evaluation, blunt neck trauma, transient ischemic attack (TIA), rule out dissection, aneurysm, or stenosis.",
      "technique": "Bolus-tracked volumetric arterial phase CTA from the aortic arch to the vertex with MIP and 3D volume-rendered reconstructions.",
      "comparison": "None available.",
      "findings": "AORTIC ARCH & SUPRA-AORTIC BRANCHES:\nNormal branching pattern of the aortic arch.\nBrachiocephalic trunk, left common carotid artery, and left subclavian artery are patent with smooth luminal contours and no dissection.\n\nEXTRACRANIAL CAROTID & VERTEBRAL ARTERIES:\nRight and left common carotid arteries (CCA) demonstrate normal caliber and smooth luminal filling.\nCarotid bifurcations and carotid bulbs are free of atheromatous plaque or stenosis.\nInternal carotid arteries (ICA) are patent throughout their cervical segments without narrowing, dissection flap, or aneurysm.\nExternal carotid arteries and branches are normal.\nVertebral arteries (V1 to V3 segments) are patent bilaterally with normal codominant / dominant caliber.\n\nINTRACRANIAL VASCULATURE & CIRCLE OF WILLIS:\nPetrous, cavernous, and supraclinoid segments of both ICAs show normal luminal opacification.\nAnterior cerebral arteries (A1 and A2 segments) and anterior communicating artery are patent.\nMiddle cerebral arteries (M1 and M2 branches) demonstrate symmetric trifurcation with normal peripheral arborization.\nBasilar artery and posterior cerebral arteries (P1 and P2 segments) are patent.\nNo intracranial aneurysm, vascular malformation (AVM/dAVF), or large vessel occlusion.",
      "impression": "Normal Head & Neck CT Angiography (CTA). Fully patent extracranial and intracranial arterial vasculature without dissection, critical stenosis, occlusion, or aneurysm.",
      "recommendation": "Clinical correlation recommended.",
      "id": "cta_head_neck"
    },
    {
      "key": "pns_ct",
      "name": "Paranasal Sinus (PNS) CT",
      "category": "CT",
      "examination": "PARANASAL SINUS (PNS) CT",
      "clinicalInformation": "Chronic sinusitis, nasal obstruction, facial pain, preoperative evaluation.",
      "technique": "High-resolution volumetric axial non-contrast CT of the paranasal sinuses and facial bones with coronal and sagittal reconstructions in bone and soft tissue algorithms.",
      "comparison": "None available.",
      "findings": "PARANASAL SINUSES:\nMaxillary Sinuses: Bilateral maxillary antra are well-aerated with normal mucoperiosteal thickness. No fluid level, retention cyst, or polyp.\nEthmoid Sinuses: Anterior and posterior ethmoid air cells are clear bilaterally. Ethmoid bullae and lamina papyracea are intact.\nFrontal Sinuses: Developed and well-aerated bilaterally with patent frontal recesses.\nSphenoid Sinuses: Fully aerated with intact bony walls and intersinus septum.\n\nOSTIOMEATAL COMPLEXES:\nBilateral ostiomeatal units (OMUs) are widely patent. Infundibula and middle meatus are clear.\n\nNASAL CAVITY & NASOPHARYNX:\nNasal septum is midline with no significant deviation or bony spur.\nBilateral superior, middle, and inferior nasal turbinates are normal in morphology without hypertrophy.\nVisualized nasopharynx is symmetric with clear airway.\n\nORBITS & ADJACENT BONES:\nBony orbital margins, cribriform plates, and skull base floor are intact.",
      "impression": "Normal Paranasal Sinus (PNS) CT. Clear, well-aerated paranasal sinuses with patent bilateral ostiomeatal complexes and midline nasal septum.",
      "recommendation": "Clinical correlation recommended.",
      "id": "pns_ct"
    },
    {
      "key": "temporal_bone_hrct",
      "name": "Temporal Bone HRCT",
      "category": "CT",
      "examination": "TEMPORAL BONE HIGH-RESOLUTION CT (HRCT)",
      "clinicalInformation": "Hearing loss, tinnitus, otalgia, chronic otitis, rule out cholesteatoma or ossicular disruption.",
      "technique": "Ultra-thin sub-millimeter axial and coronal high-resolution CT of bilateral temporal bones in high-frequency bone algorithm.",
      "comparison": "None available.",
      "findings": "EXTERNAL & MIDDLE EAR:\nExternal auditory canals are widely patent bilaterally without soft-tissue mass or bony stenosis.\nTympanic membranes are intact and of normal thickness.\nTympanic cavity (epitympanum, mesotympanum, hypotympanum) is well-aerated bilaterally without soft tissue opacity or fluid.\nOssicular Chain: Malleus, incus, and stapes are normally configured and aligned. Incudomalleolar and incudostapedial joints are intact.\nPrussak's space and scutum are intact without erosion.\n\nMASTOID:\nBilateral mastoid air cells show complete pneumatization and aeration without mucosal thickening, fluid, or bone trabecular erosion.\nSigmoid plates and tegmen tympani are intact.\n\nINNER EAR & FACIAL NERVE:\nVestibule, semicircular canals, and cochlea demonstrate normal morphology without ossification or dysplasia.\nInternal auditory canals are symmetric with normal bony margins.\nFacial nerve bony canal demonstrates normal course through its labyrinthine, tympanic, and mastoid segments without dehiscence.",
      "impression": "Normal Temporal Bone HRCT study. Well-aerated middle ear and mastoids, intact ossicular chain without erosion, and normal inner ear architecture bilaterally.",
      "recommendation": "Clinical correlation recommended.",
      "id": "temporal_bone_hrct"
    },
    {
      "key": "shoulder_ct",
      "name": "Shoulder CT",
      "category": "CT",
      "examination": "SHOULDER CT",
      "clinicalInformation": "Shoulder dislocation, instability, rule out glenoid bone loss or fracture.",
      "technique": "High-resolution volumetric axial CT of the shoulder with sagittal and coronal MPR in bone and soft tissue windows.",
      "comparison": "None available.",
      "findings": "GLENOHUMERAL JOINT:\nGlenohumeral joint is anatomic in alignment.\nGlenoid fossa demonstrates normal version and morphology without anterior or posterior rim fracture (bony Bankart lesion). No significant glenoid bone loss.\nHumeral head is spherical and congruent with intact articular cortex. No Hill-Sachs impression fracture.\nArticular joint space is maintained without narrowing or subchondral sclerosis.\n\nACROMIOCLAVICULAR JOINT & ARCH:\nAcromioclavicular joint shows normal alignment with no spurring.\nAcromion process shows normal morphology.\nCoracoid process, clavicle, and scapular body are intact without fracture.\nVisualized soft tissues about the shoulder are within normal limits.",
      "impression": "Normal Shoulder CT study. Anatomic glenohumeral alignment without fracture, glenoid rim bone loss, or Hill-Sachs deformity.",
      "recommendation": "Clinical correlation recommended.",
      "id": "shoulder_ct"
    }
  ],
  "Ultrasound": [
    {
      "key": "abdominal_us",
      "name": "Abdominal Ultrasound",
      "category": "Ultrasound",
      "examination": "ABDOMINAL ULTRASOUND",
      "clinicalInformation": "Abdominal pain, dyspepsia, general medical checkup.",
      "technique": "Real-time gray-scale and Color Doppler ultrasound examination of the abdomen using curved-array transducer (3.5–5.0 MHz).",
      "comparison": "None available.",
      "findings": "LIVER:\nNormal in size, smooth surface contour, and uniform parenchymal echogenicity.\nNo focal solid or cystic mass lesion. Intrahepatic bile ducts and hepatic vasculature are normal in caliber.\n\nGALLBLADDER & BILIARY TREE:\nGallbladder is well-distended with thin, smooth wall (<3 mm). Lumen is echo-free without calculus or polyp.\nCommon bile duct (CBD) is of normal caliber (measuring <6 mm).\n\nPANCREAS:\nHead, body, and visualized tail of the pancreas demonstrate normal size, contour, and homogeneous echotexture. Main pancreatic duct is not dilated.\n\nSPLEEN:\nNormal in size and parenchymal reflectivity. Bipolar length measures within normal limits (<12 cm). No focal splenic lesion.\n\nKIDNEYS:\nRight and left kidneys are normal in size, anatomic position, and renal axis.\nNormal cortical thickness and preserved corticomedullary differentiation.\nNo hydronephrosis, calculus, or solid/cystic renal parenchymal lesion bilaterally.\n\nGREAT VESSELS & RETROPERITONEUM:\nAbdominal aorta and inferior vena cava demonstrate normal caliber and flow dynamics.\nNo para-aortic lymphadenopathy. No free intraperitoneal fluid (ascites) in the hepatorenal recess (Morison's pouch) or splenorenal space.",
      "impression": "Normal Abdominal Ultrasound study. Preserved liver, gallbladder, pancreas, spleen, and bilateral kidneys with no focal lesion, cholelithiasis, or hydronephrosis.",
      "recommendation": "Clinical correlation recommended.",
      "id": "abdominal_us"
    },
    {
      "key": "abdominopelvic_us_female",
      "name": "Abdominopelvic Ultrasound — Female",
      "category": "Ultrasound",
      "examination": "ABDOMINOPELVIC ULTRASOUND (FEMALE)",
      "clinicalInformation": "Abdominal / lower pelvic pain, menstrual irregularity, general health check.",
      "technique": "Transabdominal real-time B-mode and Color Doppler ultrasound of the abdomen and pelvis.",
      "comparison": "None available.",
      "findings": "UPPER ABDOMEN:\nLiver: Normal size, smooth margins, and homogeneous echotexture without focal lesion.\nGallbladder: Normal wall thickness, anechoic lumen, no gallstones. CBD is not dilated.\nPancreas & Spleen: Normal dimensions and uniform parenchymal reflectivity.\nKidneys: Both kidneys demonstrate normal size, cortical thickness, and corticomedullary differentiation without calculi or hydronephrosis.\n\nPELVIC VISCERA:\nUrinary Bladder: Adequately distended with thin, smooth wall. Lumen is clear without calculus, mass, or debris.\nUterus: Anteverted, normal in size and contour with homogeneous myometrial echogenicity. No leiomyoma or adenomyosis.\nEndometrium: Regular, midline, and of normal thickness appropriate for menstrual status.\nOvaries: Right and left ovaries show normal dimensions and stroma with normal physiologic follicles. No cyst, dermoid, or adnexal mass.\nPouch of Douglas: No free pelvic fluid or collection.",
      "impression": "Normal Female Abdominopelvic Ultrasound study. Unremarkable upper abdominal organs and normal pelvic viscera without uterine fibroids, adnexal mass, or free fluid.",
      "recommendation": "Clinical correlation recommended.",
      "id": "abdominopelvic_us_female"
    },
    {
      "key": "abdominopelvic_us_male",
      "name": "Abdominopelvic Ultrasound — Male",
      "category": "Ultrasound",
      "examination": "ABDOMINOPELVIC ULTRASOUND (MALE)",
      "clinicalInformation": "Abdominal pain, urinary frequency, general health check.",
      "technique": "Transabdominal real-time B-mode and Color Doppler ultrasound of the abdomen and pelvis.",
      "comparison": "None available.",
      "findings": "UPPER ABDOMEN:\nLiver: Normal size and echogenicity without focal lesion. Intrahepatic ducts are normal.\nGallbladder: Thin-walled, lumen echo-free without stone. CBD is normal.\nPancreas & Spleen: Normal dimensions and echotexture.\nKidneys: Normal bilateral renal size, parenchymal thickness, and corticomedullary definition without hydronephrosis or nephrolithiasis.\n\nPELVIC VISCERA:\nUrinary Bladder: Well-distended with thin, regular wall (<3 mm). Lumen is clear without calculus or mass.\nProstate Gland: Normal in size, contour, and homogeneous echotexture. Capsule is intact. Estimated volume is within normal limits (<25 cc). No median lobe intravesical protrusion.\nPost-Void Residual (PVR): Negligible / insignificant post-void residual urine volume.",
      "impression": "Normal Male Abdominopelvic Ultrasound. Unremarkable abdominal organs and normal urinary bladder and prostate gland without benign prostatic hyperplasia or urinary retention.",
      "recommendation": "Clinical correlation recommended.",
      "id": "abdominopelvic_us_male"
    },
    {
      "key": "pelvic_us_female",
      "name": "Pelvic Ultrasound — Female",
      "category": "Ultrasound",
      "examination": "PELVIC ULTRASOUND (FEMALE)",
      "clinicalInformation": "Pelvic pain, dysmenorrhea, menorrhagia, fertility assessment.",
      "technique": "Transabdominal pelvic ultrasound with full urinary bladder acoustic window.",
      "comparison": "None available.",
      "findings": "URINARY BLADDER:\nWell-distended with thin, uniform wall. Echo-free lumen with no calculus or intraluminal lesion.\n\nUTERUS & CERVIX:\nUterus is anteverted, measuring normal in dimensions with smooth contour.\nMyometrial echo pattern is homogeneous without focal leiomyoma or focal mass.\nEndometrial stripe is central, well-defined, and uniform in thickness.\nCervical region is unremarkable without Nabothian cysts or cervical mass.\n\nOVARIES & ADNEXA:\nBoth right and left ovaries are visualized with normal size and volume.\nNormal baseline follicular pattern without cystic, solid, or complex adnexal mass.\nNo fluid collection in the pouch of Douglas.",
      "impression": "Normal Female Pelvic Ultrasound. Normal uterus, endometrium, and bilateral ovaries without fibroids, cysts, or pelvic free fluid.",
      "recommendation": "Clinical correlation recommended.",
      "id": "pelvic_us_female"
    },
    {
      "key": "pelvic_us_male",
      "name": "Pelvic Ultrasound — Male",
      "category": "Ultrasound",
      "examination": "PELVIC ULTRASOUND (MALE)",
      "clinicalInformation": "Dysuria, urinary hesitancy, prostate evaluation.",
      "technique": "Transabdominal pelvic ultrasound evaluation with pre- and post-void scanning.",
      "comparison": "None available.",
      "findings": "URINARY BLADDER:\nWell-distended pre-void with smooth, regular wall thickness (<3 mm).\nNo mucosal thickening, trabeculation, diverticulum, or intraluminal calculus/mass.\n\nPROSTATE GLAND & SEMINAL VESICLES:\nProstate gland demonstrates normal symmetric configuration with smooth capsule.\nEcho pattern is homogeneous without suspicious focal hypoechoic nodule or gross calcification.\nEstimated prostate dimensions and volume are within normal limits (<25 ml).\nSeminal vesicles are symmetric and unremarkable.\n\nPOST-VOID RESIDUAL:\nComplete / near-complete bladder emptying post-micturition (<20 ml residual urine).",
      "impression": "Normal Male Pelvic Ultrasound. Normal urinary bladder and prostate gland without hypertrophy or significant post-void residual volume.",
      "recommendation": "Clinical correlation recommended.",
      "id": "pelvic_us_male"
    },
    {
      "key": "obstetric_us",
      "name": "Obstetric Ultrasound (2nd & 3rd Trimester)",
      "category": "Ultrasound",
      "examination": "OBSTETRIC ULTRASOUND",
      "clinicalInformation": "Routine antenatal surveillance, gestational age and fetal growth assessment.",
      "technique": "Transabdominal real-time obstetric ultrasound scanning.",
      "comparison": "None available.",
      "findings": "FETAL PARAMETERS:\nSingle viable intrauterine pregnancy.\nFetal Presentation: Cephalic / longitudinal lie.\nFetal Heart Motion: Regular and active, within normal rate range (120–160 bpm). Fetal body and limb movements are actively observed.\n\nBIOMETRY:\nBiparietal Diameter (BPD): Normal for gestational age.\nHead Circumference (HC): Normal for gestational age.\nAbdominal Circumference (AC): Normal for gestational age.\nFemur Length (FL): Normal for gestational age.\nEstimated Fetal Weight (EFW): Appropriate for gestational age.\n\nANATOMICAL SURVEY:\nIntracranial anatomy: Ventricles, midline falx, and posterior fossa are unremarkable.\nFetal spine is intact throughout with continuous overlying skin.\nFour-chamber cardiac view is normal. Stomach bubble and urinary bladder are visualized.\nAbdominal wall is intact with normal umbilical cord insertion.\n\nLIQUOR & PLACENTA:\nAmniotic Fluid Index (AFI): Normal volume of amniotic fluid; deepest vertical pocket is within normal range.\nPlacenta: Located anteriorly / posteriorly, clear of the internal cervical os (no placenta previa). Maturity grade is appropriate for gestational age.\nInternal cervical os is closed; cervix measures of adequate length.",
      "impression": "Single live intrauterine pregnancy in cephalic presentation. Fetal biometric parameters and growth are appropriate for gestational age with normal amniotic fluid volume and normal placental position.",
      "recommendation": "Routine antenatal care.",
      "id": "obstetric_us"
    },
    {
      "key": "obstetric_bpp_us",
      "name": "Obstetric Ultrasound + Biophysical Profile (BPP)",
      "category": "Ultrasound",
      "examination": "OBSTETRIC ULTRASOUND WITH BIOPHYSICAL PROFILE (BPP)",
      "clinicalInformation": "High-risk antenatal surveillance, assessment of fetal well-being.",
      "technique": "Real-time obstetric sonography with continuous 30-minute dynamic biophysical observation.",
      "comparison": "None available.",
      "findings": "BIOMETRY & GROWTH:\nSingle viable intrauterine fetus with appropriate biometric measurements (BPD, HC, AC, FL) and normal estimated fetal weight.\n\nBIOPHYSICAL PROFILE PARAMETERS (Manning Criteria):\n1. Fetal Breathing Movements: Present (>30 seconds of continuous breathing observed) = Score 2/2\n2. Gross Fetal Body Movements: Present (>3 discrete body/limb movements observed) = Score 2/2\n3. Fetal Tone: Present (>1 active extension with return to flexion of limbs/trunk) = Score 2/2\n4. Amniotic Fluid Volume: Normal (at least one fluid pocket measuring >= 2 cm in two perpendicular planes) = Score 2/2\n5. Fetal Heart Rate Reactivity (NST equivalent): Reactive = Score 2/2\n\nTOTAL BPP SCORE: 10 / 10 (Normal, low risk of fetal asphyxia)\nPlacental position is clear of the internal os. Umbilical cord exhibits normal 3-vessel architecture.",
      "impression": "Single live intrauterine pregnancy with reassuring fetal biophysical profile (Score 10/10) and normal amniotic fluid volume.",
      "recommendation": "Continue standard antenatal care.",
      "id": "obstetric_bpp_us"
    },
    {
      "key": "early_pregnancy_us",
      "name": "1st Trimester / Early Pregnancy Ultrasound",
      "category": "Ultrasound",
      "examination": "FIRST TRIMESTER / EARLY PREGNANCY ULTRASOUND",
      "clinicalInformation": "Early pregnancy confirmation, amenorrhea, rule out ectopic pregnancy.",
      "technique": "Real-time transabdominal ultrasound with full bladder.",
      "comparison": "None available.",
      "findings": "INTRAUTERINE FINDINGS:\nA single regular intrauterine gestational sac is demonstrated with well-defined decidual reaction.\nYolk sac is visualized with normal round shape and wall thickness.\nAn active embryonic fetal pole is demonstrated within the sac.\nCrown-Rump Length (CRL): Measures concordant with estimated gestational age.\nEmbryonic cardiac pulsation is clearly identified and regular.\nNo subchorionic hemorrhage or retroplacental hematoma seen.\n\nADNEXA & MYOMETRIUM:\nBoth adnexa are clear without evidence of ectopic gestational sac or complex adnexal mass.\nMyometrium is normal with no significant fibroid. No free fluid in the cul-de-sac.",
      "impression": "Viable early single intrauterine pregnancy with documented embryonic cardiac activity. No features of ectopic gestation or threatened miscarriage.",
      "recommendation": "Routine antenatal surveillance.",
      "id": "early_pregnancy_us"
    },
    {
      "key": "scrotal_us",
      "name": "Scrotal & Inguino-Scrotal Ultrasound",
      "category": "Ultrasound",
      "examination": "SCROTAL AND INGUINO-SCROTAL ULTRASOUND",
      "clinicalInformation": "Scrotal pain, swelling, rule out testicular torsion, epididymo-orchitis, hydrocele, or hernia.",
      "technique": "High-resolution real-time gray-scale and Color Doppler sonography using high-frequency linear transducer (7.5–12.0 MHz).",
      "comparison": "None available.",
      "findings": "TESTES:\nRight Testis: Normal in size, anatomic position, and homogeneous parenchymal echogenicity. No focal intratesticular solid or cystic lesion. Normal capsular margin.\nLeft Testis: Normal in size, anatomic position, and homogeneous echotexture. No focal lesion or calcification.\nVascularity: Symmetric and normal testicular arterial blood flow demonstrated bilaterally on Color and spectral Doppler. No evidence of ischemia or torsion.\n\nEPIDIDYMIDES & CORD:\nBilateral epididymal heads, bodies, and tails show normal size and echotexture without enlargement, hypervascularity, or mass.\nSpermatic cords are normal in caliber. Pampiniform plexus veins are normal in diameter with no venous reflux or varicocele on Valsalva maneuver.\n\nSCROTAL SAC & INGUINAL CANALS:\nNo hydrocele, hematocele, or pyocele.\nScrotal wall thickness is within normal limits.\nBilateral inguinal canals are clear with no reducible or non-reducible inguinal hernia.",
      "impression": "Normal Scrotal Ultrasound study. Normal bilateral testes with preserved parenchymal echotexture and symmetric vascularity. No epididymitis, hydrocele, varicocele, or inguinal hernia.",
      "recommendation": "Clinical correlation recommended.",
      "id": "scrotal_us"
    },
    {
      "key": "breast_us",
      "name": "Breast Ultrasound (Bilateral)",
      "category": "Ultrasound",
      "examination": "BILATERAL BREAST ULTRASOUND",
      "clinicalInformation": "Breast pain, palpable lump, screening / clinical evaluation.",
      "technique": "High-resolution real-time B-mode and Color Doppler ultrasound of bilateral breasts and axillary regions using high-frequency linear transducer (10–14 MHz).",
      "comparison": "None available.",
      "findings": "RIGHT BREAST:\nSkin and nipple-areolar complex are normal in thickness without retraction.\nPremammary subcutaneous fat layer is preserved.\nFibroglandular tissue shows symmetric, uniform echotexture with no architectural distortion.\nNo focal solid mass, complex cystic lesion, or suspicious microcalcifications.\nNormal ductal caliber without ductal ectasia.\n\nLEFT BREAST:\nSkin and nipple-areolar complex are unremarkable.\nFibroglandular tissue demonstrates symmetric echotexture without focal mass or architectural distortion.\nNo solid or cystic lesion identified.\n\nAXILLAE:\nBoth right and left axillary regions demonstrate normal lymph nodes with preserved fatty hilum and thin cortex. No suspicious pathologically enlarged axillary lymphadenopathy.",
      "impression": "Normal Bilateral Breast Ultrasound study. No solid mass, suspicious cystic lesion, architectural distortion, or axillary lymphadenopathy (ACR BI-RADS Category 1: Negative).",
      "recommendation": "Routine clinical follow-up as indicated.",
      "id": "breast_us"
    },
    {
      "key": "neck_thyroid_us",
      "name": "Neck / Thyroid Ultrasound",
      "category": "Ultrasound",
      "examination": "NECK AND THYROID ULTRASOUND",
      "clinicalInformation": "Neck swelling, thyroid nodule evaluation, goiter surveillance.",
      "technique": "High-resolution sonography of the thyroid gland and cervical soft tissues using high-frequency linear probe (7.5–12 MHz).",
      "comparison": "None available.",
      "findings": "THYROID GLAND:\nRight Lobe: Normal in dimensions and parenchymal reflectivity with smooth capsule. Echotexture is homogeneous without discrete cystic or solid nodule.\nLeft Lobe: Normal in size and homogeneous echogenicity with intact capsule. No focal lesion.\nIsthmus: Measures normal in thickness with uniform echogenicity.\nVascularity: Normal symmetric parenchymal vascularity on Color Doppler without diffuse hypervascularity ('thyroid inferno').\n\nCERVICAL SOFT TISSUES & LYMPH NODES:\nParathyroid regions are clear without adenoma.\nMajor neck muscles and submandibular/parotid glands are unremarkable.\nBilateral jugular chain lymph nodes are normal in size and architecture with preserved fatty central hilum. No suspicious cervical lymphadenopathy.",
      "impression": "Normal Thyroid and Neck Ultrasound. Normal thyroid gland size, homogeneous parenchymal echotexture without nodules, and no cervical lymphadenopathy.",
      "recommendation": "Clinical correlation recommended.",
      "id": "neck_thyroid_us"
    },
    {
      "key": "chest_us",
      "name": "Chest / Thoracic Ultrasound",
      "category": "Ultrasound",
      "examination": "CHEST / THORACIC ULTRASOUND",
      "clinicalInformation": "Chest pain, dyspnea, rule out pleural effusion, pneumothorax, or consolidation.",
      "technique": "Transthoracic ultrasound of anterior, lateral, and posterior intercostal spaces using linear and phased-array probes.",
      "comparison": "None available.",
      "findings": "PLEURA & LUNG SLIDING:\nBilateral visceral-parietal pleural interfaces demonstrate normal synchronized lung sliding in real time.\nNormal horizontal reverberation A-lines present throughout. No lung point or sonographic sign of pneumothorax.\n\nPARENCHYMA & SUBPLEURAL SPACE:\nNo subpleural consolidation, hepatization, or B-line predominance.\nNo pleural-based mass lesion.\n\nPLEURAL RECESSES:\nBoth costophrenic recesses are sharp and clear.\nNo anechoic or complex pleural effusion bilaterally.\nBilateral hemidiaphragms demonstrate smooth contour and normal respiratory excursion.",
      "impression": "Normal Chest Ultrasound study. Normal lung sliding with no pleural effusion, pneumothorax, or subpleural consolidation.",
      "recommendation": "Clinical correlation recommended.",
      "id": "chest_us"
    },
    {
      "key": "knee_us",
      "name": "Musculoskeletal (Knee) Ultrasound",
      "category": "Ultrasound",
      "examination": "KNEE ULTRASOUND (MUSCULOSKELETAL)",
      "clinicalInformation": "Knee swelling, joint pain, rule out suprapatellar effusion, tendonitis, or Baker cyst.",
      "technique": "High-resolution dynamic musculoskeletal sonography using high-frequency linear probe.",
      "comparison": "None available.",
      "findings": "ANTERIOR COMPARTMENT:\nQuadriceps tendon is continuous with normal fibrillar pattern and intact patellar attachment.\nSuprapatellar pouch and prepatellar space demonstrate no abnormal fluid distension.\nPatellar tendon shows normal thickness, smooth contours, and preserved internal fibrillar architecture.\nInfrapatellar fat pad is homogeneous.\n\nMEDIAL & LATERAL COMPARTMENTS:\nMedial collateral ligament (MCL) is intact and closely applied to the bony margin.\nLateral collateral ligament (LCL) and iliotibial band are continuous with normal morphology.\n\nPOSTERIOR FOSSA (POPLITEAL REGION):\nPopliteal neurovascular bundle is patent.\nGastrocnemius-semimembranosus bursa is clear without distension or popliteal (Baker's) cyst.",
      "impression": "Normal Knee Musculoskeletal Ultrasound. Intact extensor mechanism, no suprapatellar joint effusion, and no Baker cyst or collateral ligament tear.",
      "recommendation": "Clinical correlation recommended.",
      "id": "knee_us"
    },
    {
      "key": "transfontanel_us",
      "name": "Transfontanel (Infant Neurosonogram)",
      "category": "Ultrasound",
      "examination": "TRANSFONTANEL NEUROSONOGRAPHY (INFANT BRAIN ULTRASOUND)",
      "clinicalInformation": "Infant neuro-evaluation, rule out germinal matrix hemorrhage, hydrocephalus, or hypoxic-ischemic injury.",
      "technique": "Multiplanar coronal and sagittal infant cranial sonography through the anterior fontanelle acoustic window.",
      "comparison": "None available.",
      "findings": "VENTRICULAR SYSTEM:\nLateral ventricles are symmetric and normal in caliber without ventriculomegaly or hydrocephalus.\nThird and fourth ventricles are midline and normal in size.\nChoroid plexuses demonstrate smooth contours and homogeneous echogenicity with no intraventricular clot.\n\nBRAIN PARENCHYMA & SULCI:\nCerebral parenchyma demonstrates normal periventricular echogenicity without periventricular leukomalacia (PVL) or parenchymal echodensities.\nInterhemispheric fissure is midline. Cortical sulcal pattern is appropriate for age.\nCaudothalamic grooves are clear bilaterally with no germinal matrix hemorrhage (Grade I-IV GMH absent).\n\nPOSTERIOR FOSSA:\nCerebellar hemispheres, vermis, and cisterna magna are anatomically normal.",
      "impression": "Normal Transfontanel Neurosonography. Normal ventricular dimensions and cerebral parenchymal echogenicity with no hydrocephalus, periventricular leukomalacia, or intracranial hemorrhage.",
      "recommendation": "Clinical correlation recommended.",
      "id": "transfontanel_us"
    },
    {
      "key": "carotid_doppler_us",
      "name": "Carotid Doppler Ultrasound",
      "category": "Ultrasound",
      "examination": "EXTRACRANIAL CAROTID ARTERY DOPPLER ULTRASOUND",
      "clinicalInformation": "Transient ischemic attack (TIA), bruit, stroke risk screening, dizziness.",
      "technique": "High-resolution gray-scale, Color flow Doppler, and pulsed-wave spectral Doppler analysis of the bilateral carotid and vertebral arteries.",
      "comparison": "None available.",
      "findings": "GRAY-SCALE & B-MODE MORPHOLOGY:\nBilateral Common Carotid Arteries (CCA): Normal wall thickness and luminal diameter. Intima-media thickness (IMT) measures normal (<0.9 mm).\nCarotid Bulbs: Smooth luminal margins with no atherosclerotic plaque, calcification, or thrombus.\nInternal Carotid Arteries (ICA): Proximal, mid, and distal cervical segments demonstrate clear lumen without plaque or stenosis.\nExternal Carotid Arteries (ECA): Patent with normal branching.\n\nCOLOR & SPECTRAL FLOW ANALYSIS:\nRight & Left CCA: Uniform wall-to-wall color filling with normal low-resistance spectral waveform. Normal peak systolic velocity (PSV).\nRight & Left ICA: Optimal color flow without filling defects or turbulence. Spectral analysis reveals normal low-resistance arterial flow pattern.\nRight & Left ECA: Normal high-resistance spectral waveform with characteristic temporal tap response.\nVertebral Arteries: Normal caliber, patent lumen, and appropriate antegrade (cephalad) flow bilaterally.\nInternal Jugular Veins: Widely patent and fully compressible with normal respiratory phasicity.",
      "impression": "Normal Extracranial Carotid Doppler Ultrasound. No evidence of hemodynamically significant carotid stenosis, atherosclerotic plaque, or flow disturbance. Normal antegrade vertebral artery flow bilaterally.",
      "recommendation": "Clinical correlation recommended.",
      "id": "carotid_doppler_us"
    },
    {
      "key": "renal_doppler_us",
      "name": "Renal Doppler Ultrasound",
      "category": "Ultrasound",
      "examination": "RENAL ARTERY DOPPLER ULTRASOUND",
      "clinicalInformation": "Hypertension, renal artery stenosis evaluation, renal parenchymal disease.",
      "technique": "Gray-scale, Color Doppler, and pulsed-wave spectral Doppler examination of the abdominal aorta, main renal arteries, and intrarenal arterial branches.",
      "comparison": "None available.",
      "findings": "B-MODE RENAL MORPHOLOGY:\nRight and left kidneys demonstrate normal size, cortical thickness, and corticomedullary differentiation without hydronephrosis or parenchymal thinning.\n\nMAIN RENAL ARTERIES:\nRight and left main renal arteries are traced from aortic origin to renal hilum.\nColor Doppler shows complete luminal filling without focal jetting, aliasing, or post-stenotic turbulence.\nPeak Systolic Velocity (PSV) in main renal arteries is within normal limits (<180 cm/s).\nRenal-Aortic Ratio (RAR) is normal (<3.5).\n\nINTRARENAL DOPPLER:\nInterlobar and segmental renal arteries show sharp systolic upstroke (normal acceleration time <0.07 s).\nResistive Index (RI) is normal bilaterally (normal range 0.55–0.70) with preserved early systolic compliance peak.",
      "impression": "Normal Renal Artery Doppler Ultrasound study. No evidence of hemodynamically significant main or segmental renal artery stenosis. Normal intrarenal resistive indices bilaterally.",
      "recommendation": "Clinical correlation recommended.",
      "id": "renal_doppler_us"
    },
    {
      "key": "lower_limb_venous_doppler",
      "name": "Lower Limb Venous Doppler",
      "category": "Ultrasound",
      "examination": "LOWER LIMB VENOUS DOPPLER ULTRASOUND",
      "clinicalInformation": "Leg swelling, calf pain, rule out deep vein thrombosis (DVT).",
      "technique": "Real-time B-mode compression ultrasonography, Color Doppler, and spectral analysis of the deep and superficial venous system of the lower extremity.",
      "comparison": "None available.",
      "findings": "DEEP VENOUS SYSTEM:\nCommon femoral vein (CFV), femoral vein (FV), deep femoral vein (profunda), and popliteal vein demonstrate normal caliber and thin walls.\nAnterior tibial, posterior tibial, and peroneal veins are patent.\nCompression: All deep veins completely compress with gentle transducer pressure along their entire courses.\nLumen: Anechoic lumen without acute intraluminal thrombus or chronic post-thrombotic changes.\n\nCOLOR & SPECTRAL FLOW:\nSpontaneous flow with respiratory phasicity demonstrated in all evaluated segments.\nNormal augmentation response upon distal limb compression. No venous reflux on Valsalva maneuver.\n\nSUPERFICIAL VENOUS SYSTEM:\nGreat saphenous vein (GSV) and small saphenous vein (SSV) are patent and compressible with competent saphenofemoral and saphenopopliteal junctions. No superficial thrombophlebitis or significant varicosities.",
      "impression": "Normal Lower Extremity Venous Doppler Ultrasound. Complete compressibility and normal flow dynamics across all deep and superficial veins with no evidence of deep vein thrombosis (DVT) or venous insufficiency.",
      "recommendation": "Clinical correlation recommended.",
      "id": "lower_limb_venous_doppler"
    },
    {
      "key": "lower_limb_arterial_doppler",
      "name": "Lower Limb Arterial Doppler",
      "category": "Ultrasound",
      "examination": "LOWER LIMB ARTERIAL DOPPLER ULTRASOUND",
      "clinicalInformation": "Intermittent claudication, peripheral artery disease (PAD), cold extremity.",
      "technique": "Gray-scale, Color flow mapping, and pulsed-wave spectral Doppler analysis of the lower extremity arterial tree.",
      "comparison": "None available.",
      "findings": "GRAY-SCALE & COLOR MAPPING:\nCommon femoral artery, profunda femoris, superficial femoral artery, popliteal artery, anterior tibial, posterior tibial, and dorsalis pedis arteries demonstrate normal caliber and smooth luminal outline.\nNo wall thickening, calcification, or hemodynamically significant stenosis. Complete luminal color filling without flow void or turbulence.\n\nSPECTRAL ANALYSIS:\nAll evaluated arterial segments demonstrate normal, high-resistance triphasic flow waveforms with sharp systolic acceleration, transient early diastolic reversal, and late diastolic forward flow.\nPeak systolic velocities are within normal ranges along the entire limb length.",
      "impression": "Normal Lower Extremity Arterial Doppler Ultrasound. Patent lower limb arterial tree with preserved triphasic waveforms and no evidence of significant peripheral arterial disease (PAD) or stenosis.",
      "recommendation": "Clinical correlation recommended.",
      "id": "lower_limb_arterial_doppler"
    },
    {
      "key": "lower_limb_venous_arterial_doppler",
      "name": "Lower Limb Venous & Arterial Doppler (Combined)",
      "category": "Ultrasound",
      "examination": "LOWER LIMB COMBINED VENOUS AND ARTERIAL DOPPLER",
      "clinicalInformation": "Limb swelling, pain, comprehensive vascular assessment.",
      "technique": "Comprehensive gray-scale, Color flow Doppler, and spectral analysis of both arterial and venous systems of the lower extremity.",
      "comparison": "None available.",
      "findings": "VENOUS SYSTEM:\nCommon femoral, femoral, popliteal, calf deep veins, and saphenous veins are fully compressible under transducer pressure.\nSpontaneous phasic flow with distal augmentation and no evidence of deep or superficial venous thrombosis.\n\nARTERIAL SYSTEM:\nCommon femoral, superficial femoral, popliteal, anterior tibial, posterior tibial, and dorsalis pedis arteries demonstrate normal caliber, smooth walls, and classic triphasic spectral flow waveforms without focal stenosis.\n\nSOFT TISSUES:\nNo subcutaneous edema, intramuscular collection, or aneurysm/pseudoaneurysm.",
      "impression": "Normal Lower Extremity Combined Vascular Doppler study. No deep vein thrombosis (DVT) and normal peripheral arterial perfusion with intact triphasic waveforms.",
      "recommendation": "Clinical correlation recommended.",
      "id": "lower_limb_venous_arterial_doppler"
    },
    {
      "key": "upper_limb_venous_doppler",
      "name": "Upper Limb Venous Doppler",
      "category": "Ultrasound",
      "examination": "UPPER LIMB VENOUS DOPPLER ULTRASOUND",
      "clinicalInformation": "Arm swelling, pain, catheter-related thrombosis rule-out.",
      "technique": "Gray-scale compression sonography, Color Doppler, and spectral analysis of the upper extremity veins.",
      "comparison": "None available.",
      "findings": "DEEP & SUPERFICIAL VEINS:\nInternal jugular, subclavian, axillary, brachial, radial, and ulnar veins, along with the cephalic and basilic veins, are evaluated.\nAll compressible veins demonstrate complete coaptation under gentle transducer pressure.\nSubclavian and brachiocephalic veins demonstrate normal respiratory phasicity and cardiac pulsatility with complete color filling.\nNo intraluminal thrombus or venous occlusion.",
      "impression": "Normal Upper Extremity Venous Doppler Ultrasound. Widely patent and compressible upper limb veins with no evidence of upper extremity deep or superficial vein thrombosis.",
      "recommendation": "Clinical correlation recommended.",
      "id": "upper_limb_venous_doppler"
    },
    {
      "key": "upper_limb_arterial_doppler",
      "name": "Upper Limb Arterial Doppler",
      "category": "Ultrasound",
      "examination": "UPPER LIMB ARTERIAL DOPPLER ULTRASOUND",
      "clinicalInformation": "Upper limb ischemia, Raynaud phenomenon, vascular access evaluation.",
      "technique": "Color and spectral Doppler ultrasound evaluation of the upper extremity arterial system.",
      "comparison": "None available.",
      "findings": "ARTERIAL TREE:\nSubclavian, axillary, brachial, radial, and ulnar arteries demonstrate normal anatomical course, smooth intima-media complex, and clear lumen.\nNo arterial wall calcification, plaque, aneurysm, or stenosis.\nSpectral Doppler demonstrates normal triphasic arterial flow with sharp systolic peak and preserved reverse flow component.\nPalmar arches and digital arteries show adequate terminal perfusion.",
      "impression": "Normal Upper Extremity Arterial Doppler Ultrasound. Patent arterial vasculature with preserved triphasic flow patterns and no significant stenosis or occlusion.",
      "recommendation": "Clinical correlation recommended.",
      "id": "upper_limb_arterial_doppler"
    },
    {
      "key": "upper_limb_venous_arterial_doppler",
      "name": "Upper Limb Venous & Arterial Doppler (Combined)",
      "category": "Ultrasound",
      "examination": "UPPER LIMB COMBINED VENOUS AND ARTERIAL DOPPLER",
      "clinicalInformation": "Comprehensive upper extremity vascular evaluation for pain, swelling, or trauma.",
      "technique": "Comprehensive B-mode, Color Doppler, and pulsed-wave spectral Doppler study of the upper extremity arteries and veins.",
      "comparison": "None available.",
      "findings": "VENOUS EVALUATION:\nInternal jugular, subclavian, axillary, brachial, basilic, and cephalic veins are patent, anechoic, and fully compressible without thrombosis.\n\nARTERIAL EVALUATION:\nSubclavian, axillary, brachial, radial, and ulnar arteries exhibit smooth walls and normal triphasic spectral flow waveforms without stenosis.",
      "impression": "Normal Upper Extremity Combined Vascular Doppler study. No venous thrombosis and preserved arterial perfusion throughout the upper limb.",
      "recommendation": "Clinical correlation recommended.",
      "id": "upper_limb_venous_arterial_doppler"
    }
  ]
};

export default RADIOLOGY_TEMPLATES;
