import {useEffect,useState} from 'react';
import {api} from '../api/client.js';
import {useAuth} from '../context/AuthContext.jsx';
import {useRealtime} from '../context/RealtimeContext.jsx';
import {useLocation} from 'react-router-dom';
const emptyReport={equipment:[],results:[],comments:''};
const emptyRequest={item:'',quantity:1,reason:'',priority:'Routine'};

export default function CollectionPage(){
 const {token,user}=useAuth(),location=useLocation(),{subscribe,unsubscribe}=useRealtime(),[dash,setDash]=useState(),[queue,setQueue]=useState([]),[equipment,setEquipment]=useState({equipment:[],parameters:{}}),[stock,setStock]=useState([]),[requests,setRequests]=useState([]),[tab,setTab]=useState('queue'),[selected,setSelected]=useState(),[report,setReport]=useState(emptyReport),[generated,setGenerated]=useState(),[confirmSubmit,setConfirmSubmit]=useState(false),[request,setRequest]=useState(emptyRequest),[q,setQ]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [d,que,e,s,r]=await Promise.all([api('/collection/dashboard',{token}),api(`/collection/queue?q=${encodeURIComponent(q)}`,{token}),api('/report-entry/equipment',{token}),api('/collection/stock',{token}),api('/extra-requests',{token})]);setDash(d);setQueue(que.queue);setEquipment(e);setStock(s.items);setRequests(r.requests)}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[token,q]);
 useEffect(()=>{const cb=()=>load();subscribe('collection:change',cb);subscribe('stock:change',cb);subscribe('extraRequests:change',cb);return()=>{unsubscribe('collection:change',cb);unsubscribe('stock:change',cb);unsubscribe('extraRequests:change',cb)}},[subscribe,unsubscribe]);
 useEffect(()=>{const resume=location.state?.resume;if(resume){setSelected(resume.patient);setReport({equipment:resume.equipment||[],results:resume.results||[],comments:resume.comments||''});setGenerated(null);setTab('report');setMessage('Report loaded for editing.')}},[location.state]);
 const selectEquipment=name=>{const equipmentList=report.equipment.includes(name)?report.equipment.filter(x=>x!==name):[...report.equipment,name];setGenerated(null);setReport({...report,equipment:equipmentList,results:equipmentList.flatMap(x=>equipment.parameters[x]||[])});};
 async function start(row){setBusy(true);setError('');try{await api(`/collection/patients/${row.patient._id}/start`,{token,method:'POST'});const draft=await api(`/report-entry/patients/${row.patient._id}/draft`,{token});setSelected(row.patient);setReport(draft.report||emptyReport);setGenerated(null);setTab('report');setMessage(draft.report?'Draft loaded for editing.':'Collection started and standard consumables deducted.');load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(submit){if(!selected)return;setBusy(true);setError('');try{await api(`/collection/patients/${selected._id}/report`,{token,method:'PUT',body:JSON.stringify(report)});if(submit)await api(`/collection/patients/${selected._id}/report/submit`,{token,method:'POST'});setMessage(submit?'Report submitted for approval.':'Draft report saved.');if(submit){setSelected(null);setTab('queue')}load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function generate(){if(!selected)return;setBusy(true);setError('');try{await api(`/collection/patients/${selected._id}/report`,{token,method:'PUT',body:JSON.stringify(report)});const result=await api(`/report-entry/patients/${selected._id}/generate`,{token,method:'POST'});setGenerated(result.report);setMessage('Laboratory report generated. You can print it or continue editing the draft.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submitExtra(e){e.preventDefault();if(!selected){setError('Start a collection before requesting extra items.');return}setBusy(true);setError('');try{await api('/collection/extra-requests',{token,method:'POST',body:JSON.stringify({...request,patient:selected._id})});setRequest(emptyRequest);setMessage('Extra item request submitted for approval.');load()}catch(err){setError(err.message)}finally{setBusy(false)}}
 const cards=[['Today’s collections',dash?.summary.todayCollections],['Pending collections',dash?.summary.pendingCollections],['In progress',dash?.summary.inProgress],['Pending approvals',dash?.summary.pendingApprovals],['Critical stock alerts',dash?.summary.criticalStock]];
 return <section className="page collection-page"><header className="dash-header"><div><p className="eyebrow">Laboratory technician workspace</p><h1>Welcome, {user.fullName}</h1><p className="intro">Receive paid patients, collect samples, and request approved extra consumables.</p></div><input className="global-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient ID, barcode or name"/></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<div className="reception-tabs">{[['queue','Patient queue'],['report','Result entry'],['extra','Extra request'],['stock','Available stock']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='queue'&&<><div className="enterprise-grid">{cards.map(([label,value])=><article className="enterprise-card blue" key={label}><small>{label}</small><strong>{value??'—'}</strong></article>)}</div><section className="table-card"><h2>Paid patient queue</h2>{queue.length?<table><thead><tr><th>Patient</th><th>Details</th><th>Sample types</th><th>Status</th><th/></tr></thead><tbody>{queue.map(row=><tr key={row.patient._id}><td><strong>{row.patient.name}</strong><span>{row.patient.patientId} · {row.patient.barcode}</span></td><td>{row.patient.age} · {row.patient.sex}<span>{row.patient.registrationType}</span></td><td>{row.patient.sampleTypes.map(x=>x.name).join(', ')}</td><td>{row.collection.status}</td><td><button className="primary" disabled={busy||row.collection.status==='Completed'} onClick={()=>start(row)}>{row.collection.status==='In Progress'?'Continue':'Start collection'}</button></td></tr>)}</tbody></table>:<p className="empty">No paid patients currently waiting for collection.</p>}</section></>}
 {tab==='report'&&<section className="reception-form"><div><p className="eyebrow">Laboratory report</p><h2>{selected?`${selected.name} · ${selected.patientId}`:'Select a patient from the queue'}</h2></div>{selected&&<><div><h3>Equipment used</h3><div className="sample-grid">{equipment.equipment.map(x=><button type="button" key={x} className={report.equipment.includes(x)?'sample-card chosen':'sample-card'} onClick={()=>selectEquipment(x)}>{x}</button>)}</div></div>{report.results.length>0&&<div className="result-grid">{report.results.map((x,i)=><label key={`${x.sampleName}${i}`}>{x.sampleName}<small>{x.referenceValue}</small><input required value={x.result||''} onChange={e=>{const results=[...report.results];results[i]={...x,result:e.target.value};setGenerated(null);setReport({...report,results})}} placeholder="Value from laboratory machine"/></label>)}</div>}<label>Comments<textarea value={report.comments} onChange={e=>{setGenerated(null);setReport({...report,comments:e.target.value})}}/></label><div className="form-actions"><button className="secondary" disabled={busy||!report.results.length} onClick={()=>save(false)}>Save draft</button><button className="secondary" disabled={busy||!report.results.length} onClick={generate}>Generate Print Preview</button><button className="primary" disabled={busy||!generated} onClick={()=>setConfirmSubmit(true)}>Submit for approval</button></div>{generated&&<section className="table-card"><p className="eyebrow">Print preview · Pending approval</p><h2>ETU Diagnostic Laboratory</h2><p><strong>{generated.patient?.name}</strong> · {generated.patient?.patientId} · Barcode: {generated.patient?.barcode||generated.patient?.patientId}</p><p><strong>Samples:</strong> {generated.patient?.sampleTypes?.map(x=>x.name).join(', ')||'—'}<br/><strong>Collector:</strong> {generated.technician?.fullName||user.fullName}<br/><strong>Equipment:</strong> {generated.equipment.join(', ')}</p><table><thead><tr><th>Parameter</th><th>Result</th><th>Reference range</th></tr></thead><tbody>{generated.results.map((row,i)=><tr key={i}><td>{row.sampleName}</td><td>{row.result}</td><td>{row.referenceValue}</td></tr>)}</tbody></table><p><strong>Comments:</strong> {generated.comments||'—'}</p><p className="intro">This preview cannot be printed or exported until an Admin or Approver approves the report.</p></section>}</>}</section>}
 {tab==='extra'&&<section className="reception-form"><div><p className="eyebrow">Approval required</p><h2>Extra request form</h2><p className="intro">{selected?`For ${selected.name} (${selected.patientId})`:'Start a patient collection first.'}</p></div><form onSubmit={submitExtra}><div className="form-grid"><label>Select item<select required value={request.item} onChange={e=>setRequest({...request,item:e.target.value})}><option value="">Choose an available item</option>{stock.map(item=><option key={item._id} value={item._id}>{item.itemName} — {item.remainingQuantity} {item.unit}</option>)}</select></label><label>Quantity<input type="number" min="1" max="1000" required value={request.quantity} onChange={e=>setRequest({...request,quantity:+e.target.value})}/></label><label>Priority<select value={request.priority} onChange={e=>setRequest({...request,priority:e.target.value})}><option>Routine</option><option>Urgent</option><option>Critical</option></select></label><label className="wide">Reason<textarea required minLength="3" value={request.reason} onChange={e=>setRequest({...request,reason:e.target.value})} placeholder="Why is the extra item needed?"/></label></div><button className="primary" disabled={busy||!selected}>Submit for approval</button></form><section className="table-card"><h3>Request history</h3>{requests.length?<table><thead><tr><th>Request</th><th>Item</th><th>Quantity</th><th>Status</th><th>Reason</th></tr></thead><tbody>{requests.map(r=><tr key={r._id}><td>{r.requestNumber}</td><td>{r.item?.itemName}</td><td>{r.quantity}</td><td>{r.status}</td><td>{r.reason}</td></tr>)}</tbody></table>:<p className="empty">No extra requests yet.</p>}</section></section>}
 {tab==='stock'&&<section className="table-card"><h2>Available consumables</h2><table><thead><tr><th>Item</th><th>Code</th><th>Remaining</th><th>Status</th></tr></thead><tbody>{stock.map(item=><tr key={item._id}><td>{item.itemName}</td><td>{item.itemCode}</td><td>{item.remainingQuantity} {item.unit}</td><td>{item.remainingQuantity<=item.minimumThreshold?'Low stock':'Available'}</td></tr>)}</tbody></table></section>}{confirmSubmit&&<div className="modal-backdrop"><div className="modal-content" style={{maxWidth:520}}><h2>Confirm report accuracy</h2><p>Please carefully review this report before submission. After submitting, you cannot edit, approve, export, or print it until it has been reviewed.</p><div className="form-actions"><button className="secondary" onClick={()=>setConfirmSubmit(false)}>Review Again</button><button className="primary" disabled={busy} onClick={async()=>{setConfirmSubmit(false);await save(true)}}>Submit For Approval</button></div></div></div>}</section>;
}
