import { useEffect, useMemo, useState } from 'react';
import { api } from '../api/client.js';
import { useAuth } from '../context/AuthContext.jsx';
import { useRealtime } from '../context/RealtimeContext.jsx';
import { printLabReport } from '../utils/printLabReport.js';

const today = value => new Date(value).toDateString() === new Date().toDateString();
function Card({ label, value, tone }) { return <article className={`enterprise-card ${tone}`}><small>{label}</small><strong>{value}</strong></article>; }
function ReportPreview({ report }) { const p = report.patient || {}; return <section className="table-card" style={{ margin: 0 }}><p className="eyebrow">Final report preview</p><h2>ETU Diagnostic Laboratory</h2><div className="form-grid"><p><strong>Patient:</strong> {p.name}</p><p><strong>Patient ID:</strong> {p.patientId}</p><p><strong>Barcode:</strong> {p.barcode || p.patientId}</p><p><strong>Age / Sex:</strong> {p.age || '—'} / {p.sex || '—'}</p><p><strong>Sample types:</strong> {p.sampleTypes?.map(x => x.name).join(', ') || '—'}</p><p><strong>Collector:</strong> {report.technician?.fullName || '—'}</p><p><strong>Submitted:</strong> {new Date(report.submittedDate || report.updatedDate).toLocaleString()}</p><p><strong>Status:</strong> {report.status === 'Submitted' ? 'Pending Approval' : report.status}</p></div><p><strong>Equipment:</strong> {report.equipment?.join(', ') || '—'}</p><table><thead><tr><th>Parameter</th><th>Result</th><th>Reference value</th></tr></thead><tbody>{report.results?.map((row, i) => <tr key={`${row.sampleName}-${i}`}><td>{row.sampleName}</td><td>{row.result}</td><td>{row.referenceValue || '—'}</td></tr>)}</tbody></table><p><strong>Comments:</strong> {report.comments || '—'}</p></section>; }

export default function ExtraRequestsPage() {
  const { token, user } = useAuth(); const isAdmin = user.role === 'Admin';
  const { subscribe, unsubscribe } = useRealtime();
  const [requests, setRequests] = useState([]); const [reports, setReports] = useState([]); const [reportHistory, setReportHistory] = useState([]);
  const [tab, setTab] = useState('stock'); const [stockStatus, setStockStatus] = useState('Pending'); const [reportStatus, setReportStatus] = useState('Pending'); const [query, setQuery] = useState('');
  const [comments, setComments] = useState({}); const [selected, setSelected] = useState(null); const [reason, setReason] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { const calls = [api('/extra-requests', { token })]; if (isAdmin) calls.push(api('/report-approvals/pending', { token }), api('/report-approvals/history', { token })); const [stock, pending = { reports: [] }, history = { reports: [] }] = await Promise.all(calls); setRequests(stock.requests); setReports(pending.reports); setReportHistory(history.reports); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, [token, isAdmin]);
  useEffect(() => {
    subscribe('extraRequests:change', load);
    subscribe('reports:change', load);
    return () => { unsubscribe('extraRequests:change', load); unsubscribe('reports:change', load); };
  }, [subscribe, unsubscribe]);
  const reviewStock = async (id, decision) => { setBusy(true); setError(''); try { const result = await api(`/extra-requests/${id}/review`, { token, method: 'PATCH', body: JSON.stringify({ status: decision, comments: comments[id] || '' }) }); setMessage(result.message); load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const decideReport = async status => { if (!selected || busy) return; if (status === 'Rejected' && !reason.trim()) { setError('A reason for rejection is required.'); return; } setBusy(true); setError(''); try { await api(`/report-approvals/${selected._id}`, { token, method: 'PATCH', body: JSON.stringify({ status, comments: reason }) }); setMessage(`Report ${status.toLowerCase()}.`); setSelected(null); setReason(''); load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const visibleStock = requests.filter(r => !stockStatus || r.status === stockStatus);
  const visibleReports = useMemo(() => [...reports, ...reportHistory].filter((r, index, all) => all.findIndex(x => x._id === r._id) === index).filter(r => { const status = r.status === 'Submitted' ? 'Pending' : r.status; const haystack = `${r.patient?.name || ''} ${r.patient?.patientId || ''} ${r.patient?.barcode || ''} ${r.technician?.fullName || ''}`.toLowerCase(); return (!reportStatus || status === reportStatus) && (!query || haystack.includes(query.toLowerCase())); }), [reports, reportHistory, reportStatus, query]);
  const approvedToday = reportHistory.filter(r => r.status === 'Approved' && today(r.approvedDate)); const rejectedToday = reportHistory.filter(r => r.status === 'Rejected' && today(r.rejectedDate));
  return <section className="page approval-center"><header className="page-title"><div><p className="eyebrow">Controlled laboratory decisions</p><h1>{isAdmin ? 'Approval Center' : 'Extra Item Approvals'}</h1><p className="intro">Review stock exceptions and laboratory reports from one secure workspace.</p></div></header>
    {isAdmin && <div className="enterprise-grid"><Card label="Pending Stock Requests" value={requests.filter(x => x.status === 'Pending').length} tone="blue"/><Card label="Approved Stock Requests" value={requests.filter(x => x.status === 'Approved').length} tone="green"/><Card label="Rejected Stock Requests" value={requests.filter(x => x.status === 'Rejected').length} tone="orange"/><Card label="Pending Report Approvals" value={reports.length} tone="purple"/><Card label="Approved Reports Today" value={approvedToday.length} tone="teal"/><Card label="Rejected Reports Today" value={rejectedToday.length} tone="orange"/></div>}
    {error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message}</div>}
    <div className="reception-tabs"><button className={tab === 'stock' ? 'active' : ''} onClick={() => setTab('stock')}>Extra Stock Requests</button>{isAdmin && <button className={tab === 'reports' ? 'active' : ''} onClick={() => setTab('reports')}>Laboratory Report Approval</button>}</div>
    {tab === 'stock' && <><div className="table-title"><h2>Extra stock requests</h2><select value={stockStatus} onChange={e => setStockStatus(e.target.value)}><option value="">All requests</option><option>Pending</option><option>Approved</option><option>Rejected</option></select></div><section className="table-card">{visibleStock.length ? <table><thead><tr><th>Request</th><th>Patient</th><th>Item / quantity</th><th>Reason</th><th>Requested by</th><th>Status</th><th>Decision</th></tr></thead><tbody>{visibleStock.map(r => <tr key={r._id}><td>{r.requestNumber}<span>{new Date(r.createdDate).toLocaleString()}</span></td><td>{r.patient?.name}<span>{r.patient?.patientId}</span></td><td>{r.item?.itemName}<span>{r.quantity} {r.item?.unit}</span></td><td>{r.reason}</td><td>{r.requestedBy?.fullName}</td><td>{r.status}{r.reviewedBy && <span>{r.reviewedBy.fullName}</span>}</td><td>{r.status === 'Pending' ? <div className="review-actions"><input value={comments[r._id] || ''} onChange={e => setComments({ ...comments, [r._id]: e.target.value })} placeholder="Optional note"/><button className="primary" disabled={busy} onClick={() => reviewStock(r._id, 'Approved')}>Approve</button><button className="secondary danger" disabled={busy} onClick={() => reviewStock(r._id, 'Rejected')}>Reject</button></div> : '—'}</td></tr>)}</tbody></table> : <p className="empty">No requests match this filter.</p>}</section></>}
    {tab === 'reports' && <><div className="table-title"><h2>Laboratory report approvals</h2><div className="form-actions"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search patient, ID, barcode or collector"/><select value={reportStatus} onChange={e => setReportStatus(e.target.value)}><option value="">All reports</option><option value="Pending">Pending</option><option>Approved</option><option>Rejected</option></select></div></div><section className="table-card">{visibleReports.length ? <table><thead><tr><th>Patient</th><th>Barcode</th><th>Age / Sex</th><th>Sample types</th><th>Collector</th><th>Submitted</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleReports.map(r => <tr key={r._id}><td>{r.patient?.name}<span>{r.patient?.patientId}</span></td><td>{r.patient?.barcode || r.patient?.patientId}</td><td>{r.patient?.age || '—'} / {r.patient?.sex || '—'}</td><td>{r.patient?.sampleTypes?.map(x => x.name).join(', ') || '—'}</td><td>{r.technician?.fullName || '—'}</td><td>{new Date(r.submittedDate || r.updatedDate).toLocaleString()}</td><td>{r.priority || 'Routine'}</td><td>{r.status === 'Submitted' ? 'Pending Approval' : r.status}</td><td><button className="secondary" onClick={() => { setSelected(r); setReason(r.rejectionReason || ''); }}>View Report</button>{['Submitted', 'Pending'].includes(r.status) && <><button className="primary" disabled={busy} onClick={() => { setSelected(r); setReason(''); }}>Approve / Reject</button></>}</td></tr>)}</tbody></table> : <p className="empty">No laboratory reports match this filter.</p>}</section></>}
    {selected && <div className="modal-backdrop"><div className="modal-content" style={{ maxWidth: 900 }}><header className="modal-header"><h2>Laboratory Report</h2><button className="close-button" onClick={() => setSelected(null)}>×</button></header><ReportPreview report={selected}/><div className="form-actions"><button className="secondary" onClick={()=>{try{printLabReport(selected,user)}catch(e){setError(e.message)}}}>Print Preview</button>{['Submitted', 'Pending'].includes(selected.status) && <><label className="wide">Reason for rejection (required)<textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Describe the correction required"/></label><button className="primary" disabled={busy} onClick={() => decideReport('Approved')}>{busy ? 'Saving…' : 'Approve Report'}</button><button className="secondary danger" disabled={busy} onClick={() => decideReport('Rejected')}>Reject Report</button></>}</div></div></div>}
  </section>;
}
