import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart, Bar, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../api/client.js';
import { download } from '../api/download.js';
import { useAuth } from '../context/AuthContext.jsx';
import '../styles/pages/patientManagement.css';

const money = value => `${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })} ETB`;
const palette = ['#075c91','#16a4d8','#54c4a9','#f2b13c','#7b78e7','#ef7f75'];
const emptyHospital = { name:'',code:'',phone:'',email:'',address:'',city:'',contactPerson:'',description:'',active:true };
function Toast({ notice }) { return notice ? <div className={`pm-toast ${notice.error?'error':''}`}>{notice.text}</div> : null; }
function Chart({ title, children }) { return <section className="pm-chart"><h3>{title}</h3><div className="pm-chart-space">{children}</div></section>; }

export default function PatientManagementPage() {
  const { token } = useAuth(); const [dashboard,setDashboard]=useState(null),[patients,setPatients]=useState([]),[pagination,setPagination]=useState({}),[hospitals,setHospitals]=useState([]),[samples,setSamples]=useState([]),[users,setUsers]=useState([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(null),[profile,setProfile]=useState(null),[hospitalForm,setHospitalForm]=useState(null),[filters,setFilters]=useState({q:'',period:'',patientType:'',paymentStatus:'',reportStatus:'',sampleType:'',referralHospital:'',receptionist:'',sort:'registrationDate',order:'desc'}),[page,setPage]=useState(1);
  const notify=(text,error=false)=>{setNotice({text,error});setTimeout(()=>setNotice(null),3500)};
  const query=useMemo(()=>new URLSearchParams(Object.entries({...filters,page,limit:15}).filter(([,v])=>v!=='' )).toString(),[filters,page]);
  const load = useCallback(async()=>{setLoading(true);try{const [d,p,h,s,u]=await Promise.all([api('/patient-management/dashboard',{token}),api(`/patient-management/patients?${query}`,{token}),api('/patient-management/hospitals',{token}),api('/reception/sample-types',{token}),api('/users',{token})]);setDashboard(d);setPatients(p.patients);setPagination(p.pagination);setHospitals(h.hospitals);setSamples(s.sampleTypes);setUsers(u.users.filter(user=>user.role==='Reception'));}catch(e){notify(e.message,true)}finally{setLoading(false)}},[token,query]);
  useEffect(()=>{load()},[load]);
  const change=(key,value)=>{setFilters(old=>({...old,[key]:value}));setPage(1)};
  const showProfile=async id=>{try{setProfile(await api(`/patient-management/patients/${id}`,{token}))}catch(e){notify(e.message,true)}};
  const saveHospital=async event=>{event.preventDefault();try{const method=hospitalForm._id?'PUT':'POST',url=hospitalForm._id?`/patient-management/hospitals/${hospitalForm._id}`:'/patient-management/hospitals';await api(url,{token,method,body:JSON.stringify(hospitalForm)});setHospitalForm(null);notify('Referral hospital saved.');load()}catch(e){notify(e.message,true)}};
  const updateStatus=async hospital=>{try{await api(`/patient-management/hospitals/${hospital._id}/status`,{token,method:'PATCH',body:JSON.stringify({active:!hospital.active})});load();notify(`Hospital ${hospital.active?'deactivated':'activated'}.`)}catch(e){notify(e.message,true)}};
  const removeHospital=async hospital=>{if(!window.confirm(`Remove ${hospital.name}?`))return;try{await api(`/patient-management/hospitals/${hospital._id}`,{token,method:'DELETE'});notify('Referral hospital removed.');load()}catch(e){notify(e.message,true)}};
  const cards=dashboard?[['👥','Total Registered Patients',dashboard.summary.total],['📅',"Today's Patients",dashboard.summary.today],['📆',"This Week's Patients",dashboard.summary.week],['🏥','Referral Patients',dashboard.summary.referral],['🙋','Self Patients',dashboard.summary.self],['💰',"Today's Income",money(dashboard.summary.todayIncome)],['💵','Total Income',money(dashboard.summary.totalIncome)],['🧪','Total Samples Collected',dashboard.summary.samples]]:[];
  return <div className="pm-page"><Toast notice={notice}/><div className="pm-heading"><div><p className="eyebrow">ADMINISTRATION / CENTRAL REGISTRY</p><h1>Patient Management</h1><span>Secure patient history, billing, sample and reporting oversight.</span></div><div className="pm-actions"><button onClick={()=>window.print()}>🖨 Print view</button><button onClick={()=>download(`/patient-management/exports/patients.pdf?${query}`,token)}>PDF</button><button onClick={()=>download(`/patient-management/exports/patients.csv?${query}`,token)}>CSV</button><button className="primary-button" onClick={()=>download(`/patient-management/exports/patients.xlsx?${query}`,token)}>Excel</button></div></div>
    <section className="pm-cards">{cards.map(([icon,label,value])=><article className="pm-card" key={label}><i>{icon}</i><div><small>{label}</small><strong>{value}</strong></div></article>)}</section>
    <section className="pm-panel pm-filters"><div className="pm-panel-title"><div><h2>Patient registry</h2><span>Search, filter, sort and export the visible patient records.</span></div></div><div className="pm-filter-grid"><input value={filters.q} onChange={e=>change('q',e.target.value)} placeholder="Search ID, name, phone, barcode…"/><select value={filters.period} onChange={e=>change('period',e.target.value)}><option value="">All dates</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="week">This week</option><option value="lastWeek">Last week</option><option value="month">This month</option><option value="lastMonth">Last month</option><option value="year">This year</option></select><select value={filters.patientType} onChange={e=>change('patientType',e.target.value)}><option value="">All patient types</option><option>Self</option><option>Referral</option></select><select value={filters.paymentStatus} onChange={e=>change('paymentStatus',e.target.value)}><option value="">All payments</option><option>Paid</option><option>Unpaid</option><option>Counselling</option></select><select value={filters.reportStatus} onChange={e=>change('reportStatus',e.target.value)}><option value="">All report statuses</option>{['Draft','Submitted','Pending','Approved','Ready for Printing','Rejected'].map(x=><option key={x}>{x}</option>)}</select><select value={filters.sampleType} onChange={e=>change('sampleType',e.target.value)}><option value="">All sample types</option>{samples.map(s=><option value={s._id} key={s._id}>{s.name}</option>)}</select><select value={filters.referralHospital} onChange={e=>change('referralHospital',e.target.value)}><option value="">All referral hospitals</option>{hospitals.map(h=><option key={h._id}>{h.name}</option>)}</select><select value={filters.receptionist} onChange={e=>change('receptionist',e.target.value)}><option value="">All receptionists</option>{users.map(u=><option value={u._id} key={u._id}>{u.fullName}</option>)}</select><input type="date" title="Single date" onChange={e=>change('date',e.target.value)}/><select value={`${filters.sort}:${filters.order}`} onChange={e=>{const [sort,order]=e.target.value.split(':');change('sort',sort);change('order',order)}}><option value="registrationDate:desc">Newest first</option><option value="registrationDate:asc">Oldest first</option><option value="name:asc">Name A–Z</option><option value="grandTotal:desc">Amount high–low</option></select></div></section>
    <section className="pm-panel pm-table-wrap"><div className="pm-table-scroll"><table><thead><tr>{['Patient ID','Barcode','Patient Name','Age','Sex','Phone Number','Patient Type','Referral Hospital','Sample Types','Tests','Total Paid','Payment','Receptionist','Registration','Current Status','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="16" className="pm-empty">Loading patient registry…</td></tr>:patients.length?patients.map(p=><tr key={p._id}><td><b>{p.patientId}</b></td><td>{p.barcode}</td><td>{p.name}</td><td>{p.age}</td><td>{p.sex}</td><td>{p.phone}</td><td><span className={`pm-badge ${p.registrationType.toLowerCase()}`}>{p.registrationType}</span></td><td>{p.referralHospital||'—'}</td><td title={p.samples}>{p.samples}</td><td>{p.sampleCount}</td><td>{money(p.grandTotal)}</td><td><span className={`pm-badge ${p.paymentStatus.toLowerCase()}`}>{p.paymentStatus}</span></td><td>{p.registeredBy?.[0]?.fullName||'—'}</td><td>{new Date(p.registrationDate).toLocaleString()}</td><td><span className="pm-status">{p.reportStatus}</span></td><td><button className="pm-view" onClick={()=>showProfile(p._id)}>View</button></td></tr>):<tr><td colSpan="16" className="pm-empty">No patient records match the selected filters.</td></tr>}</tbody></table></div><footer className="pm-pagination"><span>{pagination.total||0} patients</span><button disabled={page<=1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {pagination.page||1} of {pagination.pages||1}</span><button disabled={page>=pagination.pages} onClick={()=>setPage(page+1)}>Next →</button></footer></section>
    {dashboard&&<section className="pm-charts"><Chart title="Patient Registration Trend"><ResponsiveContainer><LineChart data={dashboard.charts.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey="value" stroke="#075c91" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart><Chart title="Daily Income"><ResponsiveContainer><BarChart data={dashboard.charts.income}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#16a4d8" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Gender Distribution"><ResponsiveContainer><PieChart><Pie data={dashboard.charts.gender} dataKey="value" nameKey="name" outerRadius={78} label>{dashboard.charts.gender.map((_,i)=><Cell key={i} fill={palette[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></Chart><Chart title="Age Distribution"><ResponsiveContainer><BarChart data={dashboard.charts.age}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#54c4a9" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Top Sample Types"><ResponsiveContainer><BarChart layout="vertical" data={dashboard.charts.topSamples}><XAxis type="number"/><YAxis type="category" dataKey="name" width={100}/><Tooltip/><Bar dataKey="value" fill="#7b78e7"/></BarChart></ResponsiveContainer></Chart><Chart title="Top Referral Hospitals"><ResponsiveContainer><BarChart layout="vertical" data={dashboard.charts.topHospitals}><XAxis type="number"/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="value" fill="#f2b13c"/></BarChart></ResponsiveContainer></Chart></section>}
    <section className="pm-panel"><div className="pm-panel-title"><div><h2>Referral Hospital Management</h2><span>Only active hospitals are available to Reception when registering referral patients.</span></div><button className="primary-button" onClick={()=>setHospitalForm({...emptyHospital})}>+ Add referral hospital</button></div><div className="pm-table-scroll"><table><thead><tr>{['Hospital','Code','Contact','City','Contact person','Status','Created','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{hospitals.map(h=><tr key={h._id}><td><b>{h.name}</b><small className="pm-description">{h.description}</small></td><td>{h.code||'—'}</td><td>{h.phone||h.email||'—'}</td><td>{h.city||'—'}</td><td>{h.contactPerson||'—'}</td><td><span className={`pm-badge ${h.active?'paid':'unpaid'}`}>{h.active?'Active':'Inactive'}</span></td><td>{new Date(h.createdDate).toLocaleDateString()}</td><td className="pm-row-actions"><button onClick={()=>setHospitalForm({...h})}>Edit</button><button onClick={()=>updateStatus(h)}>{h.active?'Deactivate':'Activate'}</button><button className="danger" onClick={()=>removeHospital(h)}>Delete</button></td></tr>)}</tbody></table></div></section>
    {profile&&<Profile profile={profile} close={()=>setProfile(null)}/>} {hospitalForm&&<HospitalModal value={hospitalForm} change={(key,value)=>setHospitalForm(old=>({...old,[key]:value}))} close={()=>setHospitalForm(null)} save={saveHospital}/>}</div>;
}
function Profile({profile,close}){const {patient,payment,collection,report,counselling,previousVisits}=profile;return <div className="pm-modal-backdrop"><article className="pm-modal profile"><button className="pm-close" onClick={close}>×</button><div className="pm-profile-head"><div className="pm-avatar">{patient.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><p className="eyebrow">PATIENT PROFILE</p><h2>{patient.name}</h2><span>{patient.patientId} · {patient.barcode}</span></div><button onClick={()=>window.print()}>🖨 Print profile</button></div><div className="pm-profile-grid"><Info title="Patient Information" values={{Age:patient.age,Sex:patient.sex,Phone:patient.phone,Address:patient.address||'—',Registered:new Date(patient.registrationDate).toLocaleString(),Receptionist:patient.registeredBy?.fullName||'—'}}/><Info title="Payment Information" values={{Status:patient.paymentStatus,Method:patient.paymentMethod,'Receipt Number':patient.receiptNumber||'—','Grand Total':money(patient.grandTotal),Received:payment?.receivedBy?.fullName||'—'}}/><Info title="Referral & Collection" values={{Type:patient.registrationType,'Referral Hospital':patient.referralHospital||'—','Collection Status':collection?.status||'Pending',Collector:collection?.collector?.fullName||patient.collectedBy?.fullName||'—','Approval Status':report?.approvedBy?'Approved':'Pending','Report Status':report?.status||'Not started'}}/><Info title="Medical & Counselling History" values={{'Previous Visits':previousVisits?.length||0,'Counselling Records':counselling?.length||0,'Latest Advice':counselling?.[0]?.adviceGiven||'No counseling history'}}/></div><section className="pm-sample-list"><h3>Sample Types & Prices</h3>{patient.sampleTypes.length?patient.sampleTypes.map(s=><div key={s._id}><span>{s.name}</span><b>{money(s.price)}</b></div>):<p>None — Counseling Only service</p>}</section><section className="pm-sample-list"><h3>Counseling History</h3>{counselling?.length?counselling.map(x=><div key={x._id}><span>{new Date(x.completedAt||x.createdDate).toLocaleDateString()} · {x.counselledBy?.fullName||'—'}<small>{x.adviceGiven||x.reason} · {x.recommendedTests||x.followUp||'No recommendations recorded'}</small></span><b>{x.status}</b></div>):<p>No counseling visits recorded.</p>}</section></article></div>}
function Info({title,values}){return <section className="pm-info"><h3>{title}</h3>{Object.entries(values).map(([key,value])=><div key={key}><span>{key}</span><b>{value}</b></div>)}</section>}
function HospitalModal({value,change,close,save}){return <div className="pm-modal-backdrop"><form className="pm-modal hospital-form" onSubmit={save}><button type="button" className="pm-close" onClick={close}>×</button><h2>{value._id?'Edit':'Add'} Referral Hospital</h2><div className="pm-form-grid">{[['name','Hospital name',true],['code','Hospital code'],['phone','Phone number'],['email','Email'],['address','Address'],['city','City'],['contactPerson','Contact person']].map(([key,label,required])=><label key={key}>{label}<input required={required} type={key==='email'?'email':'text'} value={value[key]||''} onChange={e=>change(key,e.target.value)}/></label>)}<label className="full">Description<textarea value={value.description||''} onChange={e=>change('description',e.target.value)}/></label></div><footer><button type="button" onClick={close}>Cancel</button><button className="primary-button">Save hospital</button></footer></form></div>}
