import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api} from '../api/client.js';
import {useAuth} from '../context/AuthContext.jsx';
import {useRealtime} from '../context/RealtimeContext.jsx';
import {printLabReport} from '../utils/printLabReport.js';

const date=value=>value?new Date(value).toLocaleString():'—';
const statusOf=report=>report.status==='Submitted'||report.status==='Pending'?'Pending Approval':report.status;
const progress=report=>{const total=report.results?.length||0,complete=report.results?.filter(row=>String(row.result||'').trim()).length||0;return total?`${complete} of ${total} results entered`:'No results entered'};
function Card({label,value,tone}){return <article className={`enterprise-card ${tone}`}><small>{label}</small><strong>{value}</strong></article>}
export default function ReportManagementPage(){
 const {token,user}=useAuth(),go=useNavigate(),{subscribe,unsubscribe}=useRealtime(),[reports,setReports]=useState([]),[tab,setTab]=useState('Draft'),[q,setQ]=useState(''),[range,setRange]=useState('All'),[selected,setSelected]=useState(),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const data=await api('/collection/reports',{token});setReports(data.reports)}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[token]);
 useEffect(()=>{subscribe('reports:change',load);return()=>unsubscribe('reports:change',load)},[subscribe,unsubscribe]);
 const counts=useMemo(()=>({Draft:reports.filter(r=>r.status==='Draft').length,Pending:reports.filter(r=>['Submitted','Pending'].includes(r.status)).length,Approved:reports.filter(r=>['Approved','Ready for Printing'].includes(r.status)).length,Rejected:reports.filter(r=>r.status==='Rejected').length,today:reports.filter(r=>new Date(r.createdDate).toDateString()===new Date().toDateString()).length}),[reports]);
 const filtered=useMemo(()=>reports.filter(r=>{const bucket=tab==='Pending'?['Submitted','Pending'].includes(r.status):tab==='Approved'?['Approved','Ready for Printing'].includes(r.status):r.status===tab;if(!bucket)return false;const text=`${r.patient?.name||''} ${r.patient?.patientId||''} ${r.patient?.barcode||''} ${(r.patient?.sampleTypes||[]).map(x=>x.name).join(' ')}`.toLowerCase();if(q&&!text.includes(q.toLowerCase()))return false;const d=new Date(r.submittedAt||r.createdDate),now=new Date();if(range==='Today')return d.toDateString()===now.toDateString();if(range==='This Week'){const start=new Date(now);start.setDate(now.getDate()-7);return d>=start}return true}),[reports,tab,q,range]);
 const remove=async r=>{if(!window.confirm(`Delete the draft for ${r.patient?.name}?`))return;try{await api(`/collection/reports/${r._id}`,{token,method:'DELETE'});setMessage('Draft deleted.');load()}catch(e){setError(e.message)}};
 const resume=r=>go('/collection',{state:{resume:r}});
 return <section className="page collector-management"><header className="page-title"><div><p className="eyebrow">Laboratory Information Management</p><h1>Report Management</h1><p className="intro">Track your reports from saved draft through quality approval.</p></div></header>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
 <div className="enterprise-grid"><Card label="Draft Reports" value={counts.Draft} tone="blue"/><Card label="Pending Approval" value={counts.Pending} tone="purple"/><Card label="Approved Reports" value={counts.Approved} tone="green"/><Card label="Rejected Reports" value={counts.Rejected} tone="orange"/><Card label="Reports Created Today" value={counts.today} tone="teal"/></div>
 <div className="reception-tabs">{[['Draft','Draft Reports'],['Pending','Pending Approval'],['Approved','Approved Reports'],['Rejected','Rejected Reports']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 <div className="table-title"><h2>{tab} reports</h2><div className="form-actions"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient, ID, barcode or sample"/><select value={range} onChange={e=>setRange(e.target.value)}><option>All</option><option>Today</option><option>This Week</option></select></div></div>
 <section className="table-card">{filtered.length?<table><thead><tr><th>Patient</th><th>Barcode / Samples</th><th>Status</th><th>{tab==='Draft'?'Progress':tab==='Approved'?'Approved by':tab==='Rejected'?'Rejection reason':'Submitted'}</th><th>Last saved / activity</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r._id}><td>{r.patient?.name}<span>{r.patient?.patientId}</span></td><td>{r.patient?.barcode||'—'}<span>{r.patient?.sampleTypes?.map(x=>x.name).join(', ')||'—'}</span></td><td>{statusOf(r)}</td><td>{tab==='Draft'?progress(r):tab==='Approved'?r.approvedBy?.fullName||'—':tab==='Rejected'?<strong className="danger">{r.rejectionReason}</strong>:date(r.submittedAt||r.submittedDate)}</td><td>{date(r.lastSavedAt||r.updatedDate)}</td><td><button className="secondary" onClick={()=>setSelected(r)}>{tab==='Draft'?'View Draft':'View Report'}</button>{tab==='Draft'&&<><button className="primary" onClick={()=>resume(r)}>▶ Continue Report Generation</button><button className="secondary danger" onClick={()=>remove(r)}>Delete Draft</button></>}{tab==='Rejected'&&<button className="primary" onClick={()=>resume(r)}>Continue & Generate Again</button>}</td></tr>)}</tbody></table>:<p className="empty">No reports match this view.</p>}</section>
 {selected&&<div className="modal-backdrop"><div className="modal-content" style={{maxWidth:850}}><header className="modal-header"><h2>Laboratory Report</h2><button className="close-button" onClick={()=>setSelected(null)}>×</button></header><p><strong>{selected.patient?.name}</strong> · {selected.patient?.patientId} · {selected.patient?.barcode}</p>{selected.rejectionReason&&<div className="alert error"><strong>Rejection reason:</strong>&nbsp;{selected.rejectionReason}</div>}<table><thead><tr><th>Parameter</th><th>Result</th><th>Reference value</th></tr></thead><tbody>{selected.results?.map((x,i)=><tr key={i}><td>{x.sampleName}</td><td>{x.result}</td><td>{x.referenceValue}</td></tr>)}</tbody></table><div className="form-actions"><button className="secondary" onClick={()=>{try{printLabReport(selected)}catch(e){setError(e.message)}}}>Print Preview</button></div></div></div>}</section>
}
