import { useState } from 'react';
import { usePreferences } from '../context/PreferencesContext.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../api/client.js';
import '../styles/pages/settings.css';

const defaults={primary:'#0873a2',secondary:'#126e98',sidebar:'#093f5d',card:'#ffffff',header:'#ffffff',button:'#0873a2',background:'#f4f8fb',textAccent:'#19313b',scope:'all'};
const options=[['stock','Reset Stock Quantities Only'],['patients','Delete Patient History'],['counselling','Delete Counseling History'],['reports','Delete Laboratory Report History'],['drafts','Delete Sample Collector Draft Reports'],['extraRequests','Delete Extra Stock Requests'],['approvalRequests','Delete Report Approval Requests'],['transactions','Delete Financial Transactions'],['notifications','Delete Notification History']];
const applyColors=c=>Object.entries({primary:'--color-primary',sidebar:'--etu-sidebar',header:'--etu-header',button:'--etu-button',background:'--color-surface',textAccent:'--color-on-surface'}).forEach(([key,css])=>document.documentElement.style.setProperty(css,c[key]));

export default function SettingsPage(){
 const {preferences,updatePreferences,t}=usePreferences(),{token}=useAuth();
 const [theme,setTheme]=useState(defaults),[selected,setSelected]=useState([]),[password,setPassword]=useState(''),[secondPassword,setSecondPassword]=useState(''),[phrase,setPhrase]=useState(''),[preview,setPreview]=useState(null),[result,setResult]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const toggle=key=>setSelected(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);
 const previewReset=async()=>{setBusy(true);try{setPreview(await api('/system/reset/preview',{token,method:'POST',body:JSON.stringify({password,selected})}));setNotice('Password verified. Review the records below.')}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const execute=async()=>{setBusy(true);try{setResult(await api('/system/reset/execute',{token,method:'POST',body:JSON.stringify({password,secondPassword,phrase,selected})}));setPreview(null)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const saveTheme=async()=>{try{const r=await api('/system/theme',{token,method:'PUT',body:JSON.stringify(theme)});applyColors(r.theme);if(theme.scope==='me')await updatePreferences({customTheme:r.theme});setNotice(theme.scope==='all'?'System theme saved for all users.':'Your personal theme has been saved.')}catch(e){setNotice(e.message)}};
 return <div className="page settings-page"><p className="eyebrow">{t('preferences')}</p><h1>Settings</h1><p className="intro">Manage laboratory interface preferences and protected operational reset tools.</p>{notice&&<div className="alert">{notice}</div>}
 <section className="settings-card"><h2>Personal display</h2><div className="setting-options"><button className={preferences.theme==='light'?'selected':''} onClick={()=>updatePreferences({theme:'light'})}>☀ <b>Light mode</b></button><button className={preferences.theme==='dark'?'selected':''} onClick={()=>updatePreferences({theme:'dark'})}>◐ <b>Dark mode</b></button></div><div className="settings-fields"><label>Time format<select value={preferences.timeFormat} onChange={e=>updatePreferences({timeFormat:e.target.value})}><option value="24">24-hour clock</option><option value="12">12-hour clock</option></select></label><label>Date format<select value={preferences.dateFormat} onChange={e=>updatePreferences({dateFormat:e.target.value})}><option value="locale">Local format</option><option value="iso">YYYY-MM-DD</option></select></label></div></section>
 <section className="settings-card"><h2>System color customization</h2><div className="theme-colors">{Object.entries(theme).filter(([key])=>key!=='scope').map(([key,value])=><label key={key}>{key}<input type="color" value={value} onChange={e=>{const next={...theme,[key]:e.target.value};setTheme(next);applyColors(next)}}/></label>)}</div><label>Apply to<select value={theme.scope} onChange={e=>setTheme({...theme,scope:e.target.value})}><option value="me">Only my account</option><option value="all">All users</option></select></label><button className="primary" onClick={saveTheme}>Apply settings</button></section>
 <section className="settings-card danger-zone"><h2>⚠ Database Reset Center</h2><p>Danger zone — master data, users, roles, stock items, categories, sample types, hospitals, equipment, and system settings are never reset.</p>{result?<div className="reset-complete"><strong>✓ {result.message}</strong><p>{result.total.toLocaleString()} selected records processed. An audit entry was recorded.</p></div>:<><div className="reset-steps"><span className={!preview?'current':'done'}>1 Select</span><span className={preview?'current':''}>2 Preview</span><span className={preview?'current':''}>3 Confirm</span><span>4 Reset</span></div><div className="reset-options">{options.map(([key,label])=><label key={key} className={selected.includes(key)?'checked':''}><input type="checkbox" checked={selected.includes(key)} onChange={()=>toggle(key)}/><span><b>{label}</b></span></label>)}</div>{!preview?<div className="reset-gate"><label>Admin password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="secondary" disabled={!selected.length||!password||busy} onClick={previewReset}>{busy?'Verifying…':'Verify password and preview'}</button></div>:<div className="reset-preview"><h3>Warning — review before continuing</h3>{preview.selected.map(item=><div className="preview-row" key={item.key}><span>{item.label}</span><strong>{item.count.toLocaleString()} records</strong></div>)}<label>Type exactly <code>UNDERSTOOD AND CONTINUE RESETTING</code><input value={phrase} onPaste={e=>e.preventDefault()} onChange={e=>setPhrase(e.target.value)}/></label><label>Final admin password confirmation<input type="password" value={secondPassword} onChange={e=>setSecondPassword(e.target.value)} autoComplete="current-password"/></label><div className="reset-actions"><button className="secondary" onClick={()=>setPreview(null)}>Back</button><button className="danger-button" disabled={busy||phrase!=='UNDERSTOOD AND CONTINUE RESETTING'||!secondPassword} onClick={execute}>{busy?'Resetting selected data…':'Permanently reset selected data'}</button></div></div>}</>}</section></div>;
}
