export const MAIN_CATEGORY_ORDER = [
  'HEMATOLOGY',
  'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'COAGULATION TEST',
  'SERUM ELECTROLYTE',
  'HORMONE',
  'SEROLOGY AND IMMUNOHEMATOLOGY',
  'BLOOD GROUP',
  'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'URINALYSIS',
  'BACTERIOLOGY / PARASITOLOGY',
  'SEMEN ANALYSIS',
  'STOOL EXAMINATION',
  'URINE AND BODY FLUID ANALYSIS',
  'INTERNAL MEDICINE SPECIALITY EXAMINATION FORM',
  'REFERRAL',
  'PATHOLOGY',
  'RADIOLOGY'
];

export const CATEGORY_MAP_ALIASES = {
  'INTERNAL MEDICINE SPECIALITY EXAMINATION FORM': [
    'INTERNAL MEDICINE SPECIALITY EXAMINATION FORM',
    'INTERNAL MEDICINE SPECIALTY EXAMINATION FORM',
    'INTERNAL MEDICINE',
    'SPECIALITY EXAMINATION FORM',
    'SPECIALTY EXAMINATION FORM'
  ],
  'PATHOLOGY': [
    'PATHOLOGY',
    'PATHOLOGY EXAMINATION',
    'PATHOLOGY TESTS',
    'BIOPSY',
    'CYTOLOGY'
  ],
  'RADIOLOGY': [
    'RADIOLOGY',
    'RADIOLOGY EXAMINATION',
    'RADIOLOGY TESTS',
    'IMAGING',
    'ULTRASOUND',
    'X-RAY',
    'CT SCAN'
  ],
  'BLOOD GROUP': [
    'BLOOD GROUP',
    'B/GROUP',
    'BLOOD GROUPING',
    'BLOOD GROUP & RH',
    'BLOOD GROUP AND RH',
    'BLOOD GROUP & RH TYPE',
    'IMMUNOHEMATOLOGY / BLOOD GROUP'
  ],
  'SEROLOGY AND IMMUNOHEMATOLOGY': [
    'SEROLOGY AND IMMUNOHEMATOLOGY',
    'SEROLOGY & IMMUNOHEMATOLOGY',
    'SEROLOGY/IMMUNOHEMATOLOGY',
    'SEROLOGY',
    'IMMUNOHEMATOLOGY'
  ],
  'HEMATOLOGY': [
    'HEMATOLOGY',
    'HAEMATOLOGY',
    'CBC',
    'COMPLETE BLOOD COUNT'
  ],
  'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS': [
    'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
    'CLINICAL CHEMISTRY',
    'CHEMISTRY',
    'LIPID PROFILE',
    'RENAL FUNCTION TESTS',
    'LIVER FUNCTION TEST',
    'OTHER CHEMISTRY TESTS'
  ],
  'COAGULATION TEST': [
    'COAGULATION TEST',
    'COAGULATION',
    'COAGULATION TESTS'
  ],
  'SERUM ELECTROLYTE': [
    'SERUM ELECTROLYTE',
    'SERUM ELECTROLYTES',
    'ELECTROLYTES',
    'ELECTROLYTE'
  ],
  'HORMONE': [
    'HORMONE',
    'HORMONES',
    'HORMONAL TESTS'
  ],
  'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP': [
    'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
    'BLOOD SUGAR TEST',
    'BLOOD SUGAR',
    'DIABETIC',
    'DM CHECKUP',
    'RBS/FBS'
  ],
  'URINALYSIS': [
    'URINALYSIS',
    'URINE ANALYSIS'
  ],
  'BACTERIOLOGY / PARASITOLOGY': [
    'BACTERIOLOGY / PARASITOLOGY',
    'BACTERIOLOGY',
    'PARASITOLOGY',
    'MICROBIOLOGY'
  ],
  'SEMEN ANALYSIS': [
    'SEMEN ANALYSIS',
    'SEMEN'
  ],
  'STOOL EXAMINATION': [
    'STOOL EXAMINATION',
    'STOOL EXAM',
    'STOOL'
  ],
  'URINE AND BODY FLUID ANALYSIS': [
    'URINE AND BODY FLUID ANALYSIS',
    'URINE AND BODY FLUID',
    'BODY FLUID',
    'BODY FLUIDS'
  ],
  'REFERRAL': [
    'REFERRAL',
    'REFERRAL TESTS'
  ]
};

export const TEST_NAME_TO_CATEGORY = {
  // Blood Group
  'BLOOD GROUP': 'BLOOD GROUP',
  'B/GROUP': 'BLOOD GROUP',
  'BLOOD GROUP & RH': 'BLOOD GROUP',
  'BLOOD GROUP & RH TYPE': 'BLOOD GROUP',
  'BLOOD GROUP AND RH': 'BLOOD GROUP',

  // Serology & Immunohematology
  'CRP': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'C-REACTIVE PROTEIN': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'C-REACTIVE PROTEIN (CRP)': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'ASO': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'ASO TITER': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'ASO TEST': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'ANTISTREPTOLYSIN O': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'RF': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'RHEUMATOID FACTOR': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'RHEUMATOID FACTOR (RF)': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WIDAL': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WIDAL TEST': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WIDAL / H/O': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WIDAL TEST (TYPHOID)': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WEIL-FELIX 0X19': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WEIL-FELIX OX19': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'WEIL FELIX': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'HIV': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'HIV TEST': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'HIV I & II': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'HBS': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'HBSAG': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'HCV': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'VDRL': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'RPR': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'RPR / VDRL': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'SYPHILIS': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'H. PYLORI AG': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'H. PYLORI AB': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'H. PYLORI AG STOOL': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'H. PYLORI AB, SERUM': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'DIRECT COOMBS': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'INDIRECT COOMBS': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'CROSSMATCH': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'ANA': 'SEROLOGY AND IMMUNOHEMATOLOGY',
  'ANA SCREEN': 'SEROLOGY AND IMMUNOHEMATOLOGY',

  // Hematology
  'CBC': 'HEMATOLOGY',
  'COMPLETE BLOOD COUNT': 'HEMATOLOGY',
  'RED BLOOD CELL COUNT (RBC)': 'HEMATOLOGY',
  'RED BLOOD CELL COUNT': 'HEMATOLOGY',
  'WHITE BLOOD CELL COUNT (WBC)': 'HEMATOLOGY',
  'WHITE BLOOD CELL COUNT': 'HEMATOLOGY',
  'HGB': 'HEMATOLOGY',
  'HEMOGLOBIN': 'HEMATOLOGY',
  'HEMOGLOBIN (HGB)': 'HEMATOLOGY',
  'HCT': 'HEMATOLOGY',
  'HEMATOCRIT': 'HEMATOLOGY',
  'HEMATOCRIT (HCT)': 'HEMATOLOGY',
  'PLATELET': 'HEMATOLOGY',
  'PLATELET COUNT': 'HEMATOLOGY',
  'MCV': 'HEMATOLOGY',
  'MCH': 'HEMATOLOGY',
  'MCHC': 'HEMATOLOGY',
  'ESR': 'HEMATOLOGY',

  // Clinical Chemistry
  'CREATININE': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'UREA': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'BUN': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'BUN / UREA': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'ALT': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'SGPT': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'AST': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'SGOT': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'ALP': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'TOTAL BILIRUBIN': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'DIRECT BILIRUBIN': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'B-TOTAL': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'B-DIRECT': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'Β-TOTAL': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'Β-DIRECT': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'URIC ACID': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'TOTAL CHOLESTEROL': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'CHOLESTEROL': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'TRIGLYCERIDES': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'TRIGLYCERIDE': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'HDL': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'LDL': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'LDH': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'ALBUMIN': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'TOTAL PROTEIN': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'PHOSPHORUS': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'PHOSPHATE': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'PHOSPHITE': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'MAGNESIUM': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'MG': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',
  'MAGNESIUM (MG)': 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS',

  // Serum Electrolyte
  'ELECTROLYTE': 'SERUM ELECTROLYTE',
  'SERUM ELECTROLYTE': 'SERUM ELECTROLYTE',
  'SODIUM': 'SERUM ELECTROLYTE',
  'POTASSIUM': 'SERUM ELECTROLYTE',
  'CHLORIDE': 'SERUM ELECTROLYTE',
  'CALCIUM': 'SERUM ELECTROLYTE',

  // Blood Sugar / Diabetic
  'GLUCOSE': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'FBS': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'FASTING BLOOD SUGAR': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'RBS': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'RANDOM BLOOD SUGAR': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'HBA1C': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',
  'HGBA1C': 'BLOOD SUGAR TEST (RBS/FBS) / DIABETIC (DM) CHECKUP',

  // Hormones
  'FSH': 'HORMONE',
  'TSH': 'HORMONE',
  'T3': 'HORMONE',
  'T4': 'HORMONE',
  'FT3': 'HORMONE',
  'FT3 — FREE TRIIODOTHYRONINE': 'HORMONE',
  'FT3 - FREE TRIIODOTHYRONINE': 'HORMONE',
  'FREE TRIIODOTHYRONINE': 'HORMONE',
  'FT4': 'HORMONE',
  'FT4 — FREE THYROXINE': 'HORMONE',
  'FT4 - FREE THYROXINE': 'HORMONE',
  'FREE THYROXINE': 'HORMONE',
  'TROPONIN': 'HORMONE',
  'CK-MB': 'HORMONE',
  'PSA': 'HORMONE',
  'CEA': 'HORMONE',
  'AFP': 'HORMONE',
  'B-HCG': 'HORMONE',
  'Β-HCG': 'HORMONE',
  'BETA-HCG': 'HORMONE',
  'VIT-D': 'HORMONE',
  'VITAMIN D': 'HORMONE',

  // Urine & Body Fluid
  '24HR URINE PROTEIN': 'URINE AND BODY FLUID ANALYSIS',
  '24 HR PROTEIN': 'URINE AND BODY FLUID ANALYSIS',
  'URINALYSIS': 'URINALYSIS',
  'URINE MICROSCOPY': 'URINALYSIS',
  'CHEMICAL ANALYSIS': 'URINALYSIS',
  'URINE CHEMICAL ANALYSIS': 'URINALYSIS',
  'ROUTINE URINALYSIS': 'URINALYSIS',
  'BF': 'URINE AND BODY FLUID ANALYSIS',
  'BODY FLUID': 'URINE AND BODY FLUID ANALYSIS',
  'BF / BODY FLUID': 'URINE AND BODY FLUID ANALYSIS'
};

export function normalizeCategoryName(rawCategory, testName = '') {
  const cleanCat = String(rawCategory || '').trim().toUpperCase();
  const cleanTest = String(testName || '').trim().toUpperCase();

  // 1. If testName matches TEST_NAME_TO_CATEGORY and rawCategory is missing or OTHER/GENERAL, resolve via testName
  if ((!cleanCat || cleanCat === 'OTHER' || cleanCat === 'OTHER CATEGORY' || cleanCat === 'GENERAL LABORATORY') && cleanTest) {
    if (TEST_NAME_TO_CATEGORY[cleanTest]) {
      return TEST_NAME_TO_CATEGORY[cleanTest];
    }
    for (const [tn, targetCat] of Object.entries(TEST_NAME_TO_CATEGORY)) {
      if (cleanTest === tn || cleanTest.includes(tn) || tn.includes(cleanTest)) {
        return targetCat;
      }
    }
  }

  if (!cleanCat || cleanCat === 'OTHER' || cleanCat === 'OTHER CATEGORY' || cleanCat === 'GENERAL LABORATORY') {
    return cleanTest ? (TEST_NAME_TO_CATEGORY[cleanTest] || 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS') : 'CLINICAL CHEMISTRY AND IMMUNOASSAY TESTS';
  }

  // Check exact match in MAIN_CATEGORY_ORDER
  if (MAIN_CATEGORY_ORDER.includes(cleanCat)) return cleanCat;

  // Check exact match in CATEGORY_MAP_ALIASES
  for (const [mainCat, aliases] of Object.entries(CATEGORY_MAP_ALIASES)) {
    if (aliases.some(alias => alias === cleanCat)) {
      return mainCat;
    }
  }

  // Check if cleanCat starts with or equals alias
  for (const [mainCat, aliases] of Object.entries(CATEGORY_MAP_ALIASES)) {
    if (aliases.some(alias => cleanCat.startsWith(alias) || alias.startsWith(cleanCat))) {
      return mainCat;
    }
  }

  return cleanCat;
}
